import type { GitCommitMessageConversationContext } from "@lcode/shared";
import type {
  ConversationRow,
  ConversationRowTarget,
  SessionPhase,
} from "@lcode/shared/lcode-protocol-v4";

interface AutoGitCommitMessageCompletedTurn {
  turnId: string;
  rowTarget: ConversationRowTarget;
}

export interface AutoGitCommitMessageTarget extends AutoGitCommitMessageCompletedTurn {
  key: string;
  conversationContext: GitCommitMessageConversationContext | null;
  currentSessionFilePaths: readonly string[];
}

export interface AutoGeneratedGitCommitMessageDraft {
  key: string;
  message: string;
  currentSessionFilePaths: readonly string[];
  gitFingerprint: string;
}

export interface AutoGitCommitMessageGateState {
  scopeKey: string;
  armed: boolean;
}

interface AutoGitCommitMessageGateInput {
  enabled: boolean;
  scopeKey: string;
  logEpoch?: string;
  phase?: SessionPhase;
  settled: boolean;
  completedTurn: AutoGitCommitMessageCompletedTurn | null;
  conversationContext?: GitCommitMessageConversationContext | null;
  currentSessionFilePaths?: readonly string[];
}

interface AutoGitCommitMessageGateResult {
  state: AutoGitCommitMessageGateState;
  /** undefined=保持当前 target；null=清空；object=发布新的完成态 target。 */
  target?: AutoGitCommitMessageTarget | null;
}

export function createAutoGitCommitMessageGateState(): AutoGitCommitMessageGateState {
  return { scopeKey: "", armed: false };
}

export function resolveLatestCompletedGitCommitMessageTurn(
  rows: readonly ConversationRow[],
): AutoGitCommitMessageCompletedTurn | null {
  const latestHeader = [...rows]
    .reverse()
    .find(
      (row): row is Extract<ConversationRow, { kind: "turnHeader" }> => row.kind === "turnHeader",
    );
  if (
    !latestHeader ||
    latestHeader.state !== "completedSuccess" ||
    !latestHeader.entityId ||
    !latestHeader.fileChanges ||
    latestHeader.fileChanges.files <= 0 ||
    latestHeader.fileChanges.state === "reverted"
  ) {
    return null;
  }

  return {
    turnId: latestHeader.turnId,
    rowTarget: { rowId: latestHeader.rowId, entityId: latestHeader.entityId },
  };
}

export function advanceAutoGitCommitMessageGate(
  previous: AutoGitCommitMessageGateState,
  input: AutoGitCommitMessageGateInput,
): AutoGitCommitMessageGateResult {
  const scopeChanged = previous.scopeKey !== input.scopeKey;
  const current = scopeChanged ? { scopeKey: input.scopeKey, armed: false } : previous;

  if (!input.enabled) {
    return {
      state: { scopeKey: input.scopeKey, armed: false },
      target: null,
    };
  }

  if (input.phase === "running") {
    return {
      state: { scopeKey: input.scopeKey, armed: true },
      target: null,
    };
  }

  if (input.phase !== "completedSuccess") {
    return {
      state: { scopeKey: input.scopeKey, armed: false },
      ...(scopeChanged || current.armed ? { target: null } : {}),
    };
  }

  // 冷恢复会直接落在 completedSuccess，但没有观察到当前 renderer 的 running 边沿。
  // 已观察到 running 时则继续等待终态行与后台工作收尾，不能用超时猜测完成。
  if (!current.armed || !input.settled || !input.completedTurn) {
    return { state: current };
  }

  return {
    state: { scopeKey: input.scopeKey, armed: false },
    target: {
      ...input.completedTurn,
      key: JSON.stringify([
        input.scopeKey,
        input.logEpoch ?? "",
        input.completedTurn.turnId,
        input.completedTurn.rowTarget.rowId,
        input.completedTurn.rowTarget.entityId ?? "",
      ]),
      conversationContext: input.conversationContext ?? null,
      currentSessionFilePaths: input.currentSessionFilePaths ?? [],
    },
  };
}

export function buildGitCommitMessageConversationContext(
  rows: readonly ConversationRow[],
  sessionId: string,
  targetTurnId: string,
): GitCommitMessageConversationContext | null {
  const messages: GitCommitMessageConversationContext["messages"] = [];
  let targetLastIndex = -1;
  for (let index = 0; index < rows.length; index += 1) {
    if (rows[index]?.turnId === targetTurnId) {
      targetLastIndex = index;
    }
  }
  const contextRows = targetLastIndex >= 0 ? rows.slice(0, targetLastIndex + 1) : rows;

  for (const row of contextRows) {
    if (row.kind === "userInput") {
      const content = row.text.trim();
      if (content) messages.push({ role: "user", content });
    } else if (row.kind === "assistantText") {
      const content = row.text.trim();
      if (content) messages.push({ role: "assistant", content });
    }
  }

  return messages.length > 0 ? { sessionId, messages } : null;
}

export function mergeCurrentSessionFilePaths(
  ...pathGroups: ReadonlyArray<readonly string[] | undefined>
): string[] {
  return Array.from(
    new Set(
      pathGroups
        .flatMap((paths) => paths ?? [])
        .map((path) => path.trim())
        .filter((path) => path.length > 0),
    ),
  );
}
