import assert from "node:assert/strict";
import test from "node:test";
import {
  buildGitCommitMessageScopeKey,
  resolveAutoGitCommitMessagePrefill,
  selectGitCommitMessageForScope,
} from "./autoCommitMessage.js";
import type { AutoGeneratedGitCommitMessageDraft } from "./autoCommitMessage.js";

const draft: AutoGeneratedGitCommitMessageDraft = {
  key: "完成轮",
  scopeKey: buildGitCommitMessageScopeKey(
    JSON.stringify(["repo", "remote-a", "session-a"]),
    "epoch-a",
  ),
  currentSessionFilePaths: ["a.ts"],
  gitFingerprint: "current",
  message: "feat: 增强中文功能",
  review: { id: "review", mode: "merged", groups: [], warnings: [] },
};
const resolve = (value: AutoGeneratedGitCommitMessageDraft, currentFingerprint: string | null) =>
  resolveAutoGitCommitMessagePrefill({
    draft: value,
    scopeKey: draft.scopeKey,
    currentFingerprint,
    staleMessage: "草稿已过期，请重新生成",
    unavailableMessage: "审核不可用",
  });

test("相同指纹采用中文消息及审核引用", () => {
  assert.deepEqual(resolve(draft, "current"), { message: draft.message, review: draft.review });
});

test("过期成功草稿不采用消息/review，返回显式错误阻止直接提交", () => {
  assert.deepEqual(resolve(draft, "changed"), {
    message: "",
    reviewError: "草稿已过期，请重新生成",
  });
});

test("生成失败的原因不因指纹变化而丢失", () => {
  const failed = { ...draft, review: undefined, message: "", reviewError: "文本审核失败" };
  assert.equal(resolve(failed, "current").reviewError, "文本审核失败");
  assert.equal(resolve(failed, null).reviewError, "文本审核失败\n草稿已过期，请重新生成");
});

test("未返回审核或空白消息不能作为已成功生成的草稿", () => {
  assert.equal(resolve({ ...draft, review: undefined }, "current").reviewError, "审核不可用");
  assert.equal(resolve({ ...draft, message: "  " }, "current").reviewError, "审核不可用");
});

test("纪要生成与审核授权独立：失败审核仍预填纪要，但过期必须丢弃", () => {
  const value = { ...draft, review: undefined, reviewError: "内容超限，请重新审核" };
  assert.deepEqual(resolve(value, "current"), {
    message: draft.message,
    reviewError: value.reviewError,
  });
  assert.deepEqual(resolve(value, "changed"), {
    message: "",
    reviewError: `${value.reviewError}\n草稿已过期，请重新生成`,
  });
});

test("相同 Git 指纹不能跨会话、远程或日志代次预填消息、审核与文件范围", () => {
  for (const [remote, session, epoch] of [
    ["remote-a", "session-b", "epoch-a"],
    ["remote-b", "session-a", "epoch-a"],
    ["remote-a", "session-a", "epoch-b"],
  ]) {
    const scopeKey = buildGitCommitMessageScopeKey(
      JSON.stringify(["repo", remote, session]),
      epoch,
    );
    assert.equal(selectGitCommitMessageForScope(draft, scopeKey), null);
    assert.deepEqual(
      resolveAutoGitCommitMessagePrefill({
        draft,
        scopeKey,
        currentFingerprint: "current",
        staleMessage: "过期",
        unavailableMessage: "不可用",
      }),
      { message: "", reviewError: "过期" },
    );
  }
  assert.equal(selectGitCommitMessageForScope(draft, draft.scopeKey), draft);
});
