import type { GitCommitMessageConversationContext } from "@lcode/shared";
import type { GitCommitReview } from "@lcode/shared";
import type {
  BackgroundWorkSummary,
  ConversationRow,
  ConversationRowTarget,
  SessionPhase,
} from "@lcode/shared/lcode-protocol-v4";

export function areGitCommitBackgroundWorksSettled(
  works: readonly Pick<BackgroundWorkSummary, "kind" | "status">[],
): boolean {
  // Bash 的运行态可能是需持续提供服务的预览，或旧版遗留的后台进程；
  // 两者都不再产出当前代码任务的完成事实，不能永久挡住 Git 草稿弹窗。
  return !works.some(
    (work) =>
      work.kind !== "bash" && (work.status === "running" || work.status === "resultPending"),
  );
}

interface AutoGitCommitMessageCompletedTurn {
  turnId: string;
  rowTarget: ConversationRowTarget;
}

export interface AutoGitCommitMessageTarget extends AutoGitCommitMessageCompletedTurn {
  key: string;
  scopeKey: string;
  conversationContext: GitCommitMessageConversationContext | null;
  currentSessionFilePaths: readonly string[];
}

export interface AutoGeneratedGitCommitMessageDraft {
  reviewError?: string;
  review?: GitCommitReview;
  key: string;
  scopeKey: string;
  message: string;
  currentSessionFilePaths: readonly string[];
  gitFingerprint: string;
}

export interface ManualGitCommitMessageRequest {
  key: string;
  scopeKey: string;
  currentSessionFilePaths: string[];
  conversationContext: GitCommitMessageConversationContext;
}

export function buildGitCommitMessageScopeKey(scopeKey: string, logEpoch?: string): string {
  return JSON.stringify([scopeKey, logEpoch ?? null]);
}

/** 渲染时拒绝异会话结果，不能依赖稍后运行的 effect 清理旧 state。 */
export function selectGitCommitMessageForScope<T extends { scopeKey: string }>(
  value: T | null | undefined,
  scopeKey: string,
): T | null {
  return value?.scopeKey === scopeKey ? value : null;
}

export function canGenerateSessionCommitSummary(input: {
  enabled: boolean;
  sessionId: string | null;
  readOnly: boolean;
  sideChat: boolean;
  phase?: SessionPhase;
  repositoryAvailable: boolean;
  repositoryDirty: boolean;
}): boolean {
  return (
    input.enabled &&
    Boolean(input.sessionId) &&
    !input.readOnly &&
    !input.sideChat &&
    input.phase === "completedSuccess" &&
    input.repositoryAvailable &&
    input.repositoryDirty
  );
}

export function resolveAutoGitCommitMessagePrefill(options: {
  draft: AutoGeneratedGitCommitMessageDraft;
  scopeKey: string;
  currentFingerprint: string | null;
  staleMessage: string;
  unavailableMessage: string;
}): Pick<AutoGeneratedGitCommitMessageDraft, "message" | "review" | "reviewError"> {
  const { draft } = options;
  if (!selectGitCommitMessageForScope(draft, options.scopeKey))
    return { message: "", reviewError: options.staleMessage };
  const stale = options.currentFingerprint !== draft.gitFingerprint;
  // 中文依据：消息不是审核授权；有效纪要可独立预填，审核错误仍禁止提交，过期则全部丢弃。
  if (stale || draft.reviewError || !draft.review || !draft.message.trim()) {
    const errors = [draft.reviewError, stale ? options.staleMessage : undefined].filter(Boolean);
    return {
      message: stale ? "" : draft.message,
      reviewError: errors.join("\n") || options.unavailableMessage,
    };
  }
  return { message: draft.message, review: draft.review };
}

export interface AutoGitCommitMessageGateState {
  scopeKey: string;
  armed: boolean;
}

interface AutoGitCommitMessageGateInput {
  enabled: boolean;
  /** Git 摘要可异步晚于 running 边沿到达；缺席期间只等待，不消费完成轮。 */
  repositoryAvailable?: boolean;
  scopeKey: string;
  logEpoch?: string;
  phase?: SessionPhase;
  settled: boolean;
  completedTurn: AutoGitCommitMessageCompletedTurn | null;
  conversationContext?: GitCommitMessageConversationContext | null;
  currentSessionFilePaths?: readonly string[];
}

interface AutoGitCommitMessageGateResult {
  state: AutoGitCommitMessageGateState;
  /** undefined=保持当前 target；null=清空；object=发布新的完成态 target。 */
  target?: AutoGitCommitMessageTarget | null;
}

export function createAutoGitCommitMessageGateState(): AutoGitCommitMessageGateState {
  return { scopeKey: "", armed: false };
}

export interface AutoGitCommitMessageAutoOpenInput {
  actionAvailable: boolean;
  commitDialogOpen: boolean;
  consumedDraftKey: string | null;
  draftKey: string | null | undefined;
}

export function shouldAutoOpenGitCommitDialog(input: AutoGitCommitMessageAutoOpenInput): boolean {
  return Boolean(
    input.actionAvailable &&
    !input.commitDialogOpen &&
    input.draftKey &&
    input.draftKey !== input.consumedDraftKey,
  );
}

export function resolveLatestCompletedGitCommitMessageTurn(
  rows: readonly ConversationRow[],
  allowMissingFileChanges = false,
): AutoGitCommitMessageCompletedTurn | null {
  const latestHeader = [...rows]
    .reverse()
    .find(
      (row): row is Extract<ConversationRow, { kind: "turnHeader" }> => row.kind === "turnHeader",
    );
  if (
    !latestHeader ||
    latestHeader.state !== "completedSuccess" ||
    !latestHeader.entityId ||
    (!allowMissingFileChanges &&
      (!latestHeader.fileChanges ||
        latestHeader.fileChanges.files <= 0 ||
        latestHeader.fileChanges.state === "reverted"))
  ) {
    return null;
  }

  return {
    turnId: latestHeader.turnId,
    rowTarget: { rowId: latestHeader.rowId, entityId: latestHeader.entityId },
  };
}

export function advanceAutoGitCommitMessageGate(
  previous: AutoGitCommitMessageGateState,
  input: AutoGitCommitMessageGateInput,
): AutoGitCommitMessageGateResult {
  const scopeKey = buildGitCommitMessageScopeKey(input.scopeKey, input.logEpoch);
  const scopeChanged = previous.scopeKey !== scopeKey;
  const current = scopeChanged ? { scopeKey, armed: false } : previous;

  if (!input.enabled) {
    return {
      state: { scopeKey, armed: false },
      target: null,
    };
  }

  if (input.phase === "running") {
    return {
      state: { scopeKey, armed: true },
      target: null,
    };
  }

  if (input.phase !== "completedSuccess") {
    return {
      state: { scopeKey, armed: false },
      ...(scopeChanged || current.armed ? { target: null } : {}),
    };
  }

  // 冷恢复会直接落在 completedSuccess，但没有观察到当前 renderer 的 running 边沿。
  // 已观察到 running 时则继续等待终态行与后台工作收尾，不能用超时猜测完成。
  if (
    !current.armed ||
    !input.settled ||
    !input.completedTurn ||
    input.repositoryAvailable === false
  ) {
    return { state: current, ...(scopeChanged ? { target: null } : {}) };
  }

  return {
    state: { scopeKey, armed: false },
    target: {
      ...input.completedTurn,
      scopeKey,
      key: JSON.stringify([
        scopeKey,
        input.completedTurn.turnId,
        input.completedTurn.rowTarget.rowId,
        input.completedTurn.rowTarget.entityId ?? "",
      ]),
      conversationContext: input.conversationContext ?? null,
      currentSessionFilePaths: input.currentSessionFilePaths ?? [],
    },
  };
}

export function buildGitCommitMessageConversationContext(
  rows: readonly ConversationRow[],
  sessionId: string,
  targetTurnId: string,
): GitCommitMessageConversationContext | null {
  const messages: GitCommitMessageConversationContext["messages"] = [];
  let targetLastIndex = -1;
  for (let index = 0; index < rows.length; index += 1) {
    if (rows[index]?.turnId === targetTurnId) {
      targetLastIndex = index;
    }
  }
  const contextRows = targetLastIndex >= 0 ? rows.slice(0, targetLastIndex + 1) : rows;

  for (const row of contextRows) {
    if (row.kind === "userInput") {
      const content = row.text.trim();
      if (content) messages.push({ role: "user", content });
    } else if (row.kind === "assistantText") {
      const content = row.text.trim();
      if (content) messages.push({ role: "assistant", content });
    }
  }

  return messages.length > 0 ? { sessionId, messages } : null;
}

export function mergeCurrentSessionFilePaths(
  ...pathGroups: ReadonlyArray<readonly string[] | undefined>
): string[] {
  return Array.from(
    new Set(
      pathGroups
        .flatMap((paths) => paths ?? [])
        .map((path) => path.trim())
        .filter((path) => path.length > 0),
    ),
  );
}
