import assert from "node:assert/strict";
import test from "node:test";
import { resolveAutoGitCommitMessagePrefill } from "./autoCommitMessage.js";
import type { AutoGeneratedGitCommitMessageDraft } from "./autoCommitMessage.js";

const draft: AutoGeneratedGitCommitMessageDraft = {
  key: "完成轮",
  currentSessionFilePaths: ["a.ts"],
  gitFingerprint: "current",
  message: "feat: 增强中文功能",
  review: { id: "review", mode: "merged", groups: [], warnings: [] },
};
const resolve = (value: AutoGeneratedGitCommitMessageDraft, currentFingerprint: string | null) =>
  resolveAutoGitCommitMessagePrefill({
    draft: value,
    currentFingerprint,
    staleMessage: "草稿已过期，请重新生成",
    unavailableMessage: "审核不可用",
  });

test("相同指纹采用中文消息及审核引用", () => {
  assert.deepEqual(resolve(draft, "current"), { message: draft.message, review: draft.review });
});

test("过期成功草稿不采用消息/review，返回显式错误阻止直接提交", () => {
  assert.deepEqual(resolve(draft, "changed"), {
    message: "",
    reviewError: "草稿已过期，请重新生成",
  });
});

test("生成失败的原因不因指纹变化而丢失", () => {
  const failed = { ...draft, review: undefined, message: "", reviewError: "文本审核失败" };
  assert.equal(resolve(failed, "current").reviewError, "文本审核失败");
  assert.equal(resolve(failed, null).reviewError, "文本审核失败\n草稿已过期，请重新生成");
});

test("未返回审核或空白消息不能作为已成功生成的草稿", () => {
  assert.equal(resolve({ ...draft, review: undefined }, "current").reviewError, "审核不可用");
  assert.equal(resolve({ ...draft, message: "  " }, "current").reviewError, "审核不可用");
});
