/* eslint-disable max-lines -- 顶部 Git 操作当前集中承载 trigger、commit dialog 和 push dialog；先按工作流边界收口，避免为了拆行数把状态机打散。 */
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type FormEvent,
  type KeyboardEvent,
  type ReactNode,
} from "react";
import type {
  GitCommitMessageConversationContext,
  GitIdentity,
  GitCommitReview,
  GitRepositorySummary,
  LCodeTaskChangeSummary,
} from "@lcode/shared";
import { cn } from "@/components/lib/utils.js";
import { Button } from "@/components/ui/button.js";
import { Command, CommandItem, CommandList, CommandShortcut } from "@/components/ui/command.js";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog.js";
import { Textarea } from "@/components/ui/textarea.js";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip.js";
import { toast } from "@/components/ui/toast.js";
import {
  buildGitBranchCommitPreviewFiles,
  getGitBranchCommitTotals,
  resolveGitBranchTriggerLabel,
} from "@/git-branch-switcher/display.js";
import { GitBranchSwitcher } from "@/GitBranchSwitcher.js";
import { hasGitCommitIdentity } from "@/git-branch-switcher/switchAssist.js";
import {
  canUseGitActionMenu,
  canPushGitBranch,
  resolveGitActionMenuPrimaryAction,
} from "@/git-action-menu/display.js";
import {
  buildGitChangesFingerprint,
  filterCommitPreviewFilesByPaths,
  getCurrentSessionFilePaths,
} from "@/git-action-menu/currentSessionFileScope.js";
import {
  mergeCurrentSessionFilePaths,
  resolveAutoGitCommitMessagePrefill,
  type AutoGeneratedGitCommitMessageDraft,
  type ManualGitCommitMessageRequest,
} from "@/git-action-menu/autoCommitMessage.js";
import {
  GitCommitDialogLifecycle,
  type GitCommitDialogSource,
} from "@/git-action-menu/gitCommitDialogLifecycle.js";
import { useServices } from "@/hooks/useServices.js";
import { useGitCommitReview } from "@/hooks/useGitCommitReview.js";
import { GitCommitReviewPanel } from "@/git-action-menu/GitCommitReviewPanel.js";
import { selectCommitReviewGroup } from "@/git-action-menu/commitReviewModel.js";
import { useLCodeIntl } from "@/i18n/IntlProvider.js";
import { getErrorMessage } from "@/lib/errorMessage.js";
import { runUserAction } from "@/lib/userActionTelemetry.js";
import { formatCommandShortcutLabel, matchesPrimaryShortcut } from "@/lib/keyboardShortcuts.js";
import { logger } from "@/logger.js";
import {
  AlertCircleIcon,
  ArrowUpFromLine,
  CheckIcon,
  CloudUploadIcon,
  GitBranchIcon,
  GitCommitIcon,
  LoaderIcon,
  SparklesIcon,
} from "lucide-react";

interface GitActionMenuProps {
  workspacePath: string;
  workspaceIdentity?: string;
  gitSummary: GitRepositorySummary;
  activeTaskChangeSummary?: LCodeTaskChangeSummary | null;
  commitMessageConversationContext?: GitCommitMessageConversationContext | null;
  autoGeneratedCommitMessageDraft?: AutoGeneratedGitCommitMessageDraft | null;
  dialogScopeKey?: string;
  manualCommitMessageRequest?: ManualGitCommitMessageRequest | null;
  onManualCommitMessageSettled?: (key: string) => void;
  onRefreshGit: () => void;
  className?: string;
  triggerIconOnly?: boolean;
  triggerLayout?: "header" | "status-row";
}

type GitCommitPreviewFile = ReturnType<typeof buildGitBranchCommitPreviewFiles>[number];

const COMMIT_DIALOG_ACTION_IDS = ["commit", "commitAndPush", "push"] as const;
const GIT_COMMIT_MESSAGE_TEXTAREA_ID = "git-action-menu-commit-message";
const TID_GIT_ACTION_TRIGGER = "git-action-trigger";
const TID_GIT_COMMIT_ACTION_COMMAND = "git-commit-action-command";
const TID_GIT_COMMIT_ACTION_ITEM = "git-commit-action-item";
const TID_GIT_COMMIT_DIALOG = "git-commit-dialog";
const TID_GIT_COMMIT_GENERATE_BUTTON = "git-commit-generate-button";
const TID_GIT_COMMIT_INCLUDE_UNSTAGED = "git-commit-include-unstaged";
const TID_GIT_COMMIT_MESSAGE_INPUT = "git-commit-message-input";

type CommitDialogActionId = (typeof COMMIT_DIALOG_ACTION_IDS)[number];

function gitCommitActionItemTestId(actionId: CommitDialogActionId): string {
  return `${TID_GIT_COMMIT_ACTION_ITEM}-${actionId}`;
}

function isCommitDialogActionId(value: string): value is CommitDialogActionId {
  return COMMIT_DIALOG_ACTION_IDS.includes(value as CommitDialogActionId);
}

function isCommitMessageTextAreaTarget(target: EventTarget | null): target is HTMLTextAreaElement {
  return target instanceof HTMLTextAreaElement && target.id === GIT_COMMIT_MESSAGE_TEXTAREA_ID;
}

interface GitCommitDialogState {
  summary: GitRepositorySummary;
  identity: GitIdentity | null;
  activeTaskChangeSummary: LCodeTaskChangeSummary | null;
  currentSessionFilePaths?: string[];
  stagedFiles: GitCommitPreviewFile[];
  unstagedFiles: GitCommitPreviewFile[];
}

interface GitCommitDialogProps {
  reviewError: string | null;
  review: GitCommitReview | null;
  reviewPosition: number;
  reviewAcknowledged: boolean;
  reviewCanSubmit: boolean;
  onReviewAcknowledge: (value: boolean) => void;
  onManualFallback: () => void;
  open: boolean;
  loading: boolean;
  state: GitCommitDialogState | null;
  workspacePath: string;
  message: string;
  error: string | null;
  mutationPending: boolean;
  generationPending: boolean;
  includeUnstaged: boolean;
  pushEnabled: boolean;
  onRefreshGit: () => void;
  onOpenChange: (nextOpen: boolean) => void;
  onMessageChange: (nextValue: string) => void;
  onIncludeUnstagedChange: (nextValue: boolean) => void;
  onGenerateMessage: () => void;
  onSubmit: () => void;
  onSubmitAndPush: () => void;
  onPushOnly: () => void;
  onVisible: () => void;
  onRetryLoad: () => void;
}

function getCommitDialogFiles(
  state: GitCommitDialogState,
  includeUnstaged: boolean,
): GitCommitPreviewFile[] {
  return includeUnstaged ? [...state.unstagedFiles, ...state.stagedFiles] : state.stagedFiles;
}

function getCommitDialogStagePaths(
  state: GitCommitDialogState,
  includeUnstaged: boolean,
): string[] {
  return Array.from(
    new Set(getCommitDialogFiles(state, includeUnstaged).map((file) => file.stagePath)),
  );
}

function CommitCommandActionItem({
  id,
  icon,
  label,
  shortcutLabel,
  disabled,
  loading,
  onSelect,
}: {
  id: CommitDialogActionId;
  icon: ReactNode;
  label: string;
  shortcutLabel?: string;
  disabled?: boolean;
  loading?: boolean;
  onSelect: () => void;
}) {
  return (
    <CommandItem
      data-testid={gitCommitActionItemTestId(id)}
      value={id}
      disabled={disabled}
      onSelect={() => {
        if (!disabled) {
          onSelect();
        }
      }}
      className={cn(
        "h-9 px-2.5 py-1.5 font-medium",
        disabled ? "cursor-default text-foreground-subtlest" : "text-foreground",
      )}
    >
      <span className="flex size-5 shrink-0 items-center justify-center">
        {loading ? <LoaderIcon className="size-4 animate-spin" /> : icon}
      </span>
      <span className="min-w-0 flex-1 truncate">{label}</span>
      {shortcutLabel ? <CommandShortcut>{shortcutLabel}</CommandShortcut> : null}
    </CommandItem>
  );
}

function GitCommitDialog({
  reviewError,
  review,
  reviewPosition,
  reviewAcknowledged,
  reviewCanSubmit,
  onReviewAcknowledge,
  onManualFallback,
  open,
  loading,
  state,
  workspacePath,
  message,
  error,
  mutationPending,
  generationPending,
  includeUnstaged,
  pushEnabled,
  onRefreshGit,
  onOpenChange,
  onMessageChange,
  onIncludeUnstagedChange,
  onGenerateMessage,
  onSubmit,
  onSubmitAndPush,
  onPushOnly,
  onVisible,
  onRetryLoad,
}: GitCommitDialogProps) {
  const { intl, locale } = useLCodeIntl();
  const [selectedActionId, setSelectedActionId] = useState<CommitDialogActionId>("commit");
  const messageTextareaRef = useRef<HTMLTextAreaElement | null>(null);
  const messageInputFocusedOnOpenRef = useRef(false);
  const dialogElementRef = useRef<HTMLDivElement | null>(null);
  const reportVisible = useCallback(() => {
    const element = dialogElementRef.current;
    if (!element || !element.isConnected) return;
    const style = getComputedStyle(element);
    if (
      element.getBoundingClientRect().width > 0 &&
      style.display !== "none" &&
      style.visibility !== "hidden" &&
      Number(style.opacity) > 0
    )
      onVisible();
  }, [onVisible]);
  useEffect(() => {
    if (!open) return;
    const frame = requestAnimationFrame(reportVisible);
    return () => cancelAnimationFrame(frame);
  }, [open, reportVisible]);
  const numberFormatter = new Intl.NumberFormat(locale);
  const hasIdentity = hasGitCommitIdentity(state?.identity ?? null);
  const messageReady = message.trim().length > 0;
  const actionPending = mutationPending || generationPending;
  const selectedFiles = state ? getCommitDialogFiles(state, includeUnstaged) : [];
  const stagePaths = state ? getCommitDialogStagePaths(state, includeUnstaged) : [];
  const dirtyFileCount = state ? getCommitDialogStagePaths(state, true).length : 0;
  const { fileCount, totalAdded, totalRemoved } = getGitBranchCommitTotals(selectedFiles);
  const displayChangeSummary = state?.activeTaskChangeSummary ?? null;
  const reviewGroup = selectCommitReviewGroup(review, reviewPosition);
  const displayAdded = reviewGroup
    ? reviewGroup.files.reduce((sum, file) => sum + file.added, 0)
    : (displayChangeSummary?.added ?? totalAdded);
  const displayRemoved = reviewGroup
    ? reviewGroup.files.reduce((sum, file) => sum + file.removed, 0)
    : (displayChangeSummary?.removed ?? totalRemoved);
  const hasSelectedChanges = stagePaths.length > 0;
  const hasUnstagedChanges = Boolean(state?.unstagedFiles.length);
  const commitActionDisabled =
    actionPending ||
    !reviewCanSubmit ||
    !hasSelectedChanges ||
    (!hasIdentity && state?.identity !== null);
  const pushOnlyDisabled = actionPending || !pushEnabled;
  const commitShortcutLabel = formatCommandShortcutLabel("⏎");
  const commitActions = useMemo(
    () => [
      {
        id: "commit" as const,
        icon: <GitCommitIcon className="size-4" />,
        label: intl.formatMessage({
          id: "git.actionMenu.commitDialog.action.commit",
        }),
        disabled: commitActionDisabled,
        loading: mutationPending,
        onSelect: onSubmit,
      },
      {
        id: "commitAndPush" as const,
        icon: <CloudUploadIcon className="size-4" />,
        label: intl.formatMessage({
          id: "git.actionMenu.commitDialog.action.commitAndPush",
        }),
        disabled:
          commitActionDisabled || Boolean(review && reviewPosition < review.groups.length - 1),
        loading: mutationPending,
        onSelect: onSubmitAndPush,
      },
      {
        id: "push" as const,
        icon: <CloudUploadIcon className="size-4" />,
        label: intl.formatMessage({
          id: "git.actionMenu.push",
        }),
        disabled: pushOnlyDisabled,
        loading: false,
        onSelect: onPushOnly,
      },
    ],
    [
      commitActionDisabled,
      intl,
      mutationPending,
      onPushOnly,
      onSubmit,
      onSubmitAndPush,
      pushOnlyDisabled,
      review,
      reviewPosition,
    ],
  );

  useEffect(() => {
    if (open) {
      setSelectedActionId("commit");
    }
  }, [open]);

  useEffect(() => {
    if (!open) {
      messageInputFocusedOnOpenRef.current = false;
      return;
    }
    if (loading || !state || actionPending || messageInputFocusedOnOpenRef.current) {
      return;
    }

    const frameId = window.requestAnimationFrame(() => {
      // 打开弹窗后的默认焦点要落在提交信息里，方便立即编辑或生成后微调。
      messageTextareaRef.current?.focus();
      messageInputFocusedOnOpenRef.current = true;
    });
    return () => window.cancelAnimationFrame(frameId);
  }, [actionPending, loading, open, state]);

  useEffect(() => {
    // 弹窗加载 Git 状态前提交动作会短暂不可用，不能在 loading 阶段把默认选择跳到推送。
    if (!open || loading || !state || actionPending || !reviewCanSubmit) {
      return;
    }

    const selectedAction = commitActions.find((action) => action.id === selectedActionId);
    if (selectedAction && !selectedAction.disabled) {
      return;
    }

    const firstEnabledAction = commitActions.find((action) => !action.disabled);
    if (firstEnabledAction && firstEnabledAction.id !== selectedActionId) {
      setSelectedActionId(firstEnabledAction.id);
    }
  }, [actionPending, commitActions, loading, open, selectedActionId, state, reviewCanSubmit]);

  const triggerSelectedAction = useCallback(() => {
    const selectedAction = commitActions.find((action) => action.id === selectedActionId);
    if (!selectedAction || selectedAction.disabled) {
      return;
    }
    selectedAction.onSelect();
  }, [commitActions, selectedActionId]);

  const selectAdjacentAction = useCallback(
    (direction: 1 | -1) => {
      setSelectedActionId((currentActionId) => {
        const enabledActions = commitActions.filter((action) => !action.disabled);
        if (enabledActions.length === 0) {
          return currentActionId;
        }

        const currentIndex = enabledActions.findIndex((action) => action.id === currentActionId);
        if (currentIndex === -1) {
          return enabledActions[0]?.id ?? currentActionId;
        }

        const nextIndex =
          (currentIndex + direction + enabledActions.length) % enabledActions.length;
        return enabledActions[nextIndex]?.id ?? currentActionId;
      });
    },
    [commitActions],
  );

  const handleActionCommandKeyDown = useCallback(
    (event: KeyboardEvent<HTMLDivElement>) => {
      if (event.key !== "ArrowDown" && event.key !== "ArrowUp") {
        return;
      }

      event.preventDefault();
      event.stopPropagation();
      selectAdjacentAction(event.key === "ArrowDown" ? 1 : -1);
    },
    [selectAdjacentAction],
  );

  const handleDialogKeyDown = useCallback(
    (event: KeyboardEvent<HTMLFormElement>) => {
      if (
        isCommitMessageTextAreaTarget(event.target) &&
        (event.key === "ArrowDown" || event.key === "ArrowUp")
      ) {
        // 输入框保持焦点时也允许切换下方 Command 操作，避免键盘流断掉。
        event.preventDefault();
        event.stopPropagation();
        selectAdjacentAction(event.key === "ArrowDown" ? 1 : -1);
        return;
      }

      if (!matchesPrimaryShortcut(event, "Enter")) {
        return;
      }
      event.preventDefault();
      event.stopPropagation();
      triggerSelectedAction();
    },
    [selectAdjacentAction, triggerSelectedAction],
  );

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        ref={dialogElementRef}
        onAnimationEnd={reportVisible}
        data-testid={TID_GIT_COMMIT_DIALOG}
        showCloseButton={false}
        // 具体 max-w 会覆盖 Dialog 的默认视口余量；显式限制宽度，保留已有审核滚动边界。
        className="max-h-[85dvh] w-[calc(100%-2rem)] max-w-md gap-0 overflow-y-auto border-popover-border bg-popover p-0 shadow-lg"
        onOpenAutoFocus={(event) => {
          reportVisible();
          if (!loading && state && !actionPending) {
            event.preventDefault();
          }
        }}
      >
        <DialogTitle className="sr-only">
          {intl.formatMessage({ id: "git.actionMenu.commitDialog.title" })}
        </DialogTitle>
        <DialogDescription className="sr-only">
          {intl.formatMessage({
            id: review ? "git.review.frozen" : "git.actionMenu.commitDialog.description",
          })}
        </DialogDescription>
        {loading ? (
          <div className="flex h-56 items-center justify-center px-5 py-5 text-foreground-subtle">
            <LoaderIcon className="size-5 animate-spin" />
          </div>
        ) : state ? (
          <form
            className="space-y-0"
            onKeyDownCapture={handleDialogKeyDown}
            onSubmit={(event: FormEvent<HTMLFormElement>) => {
              event.preventDefault();
              triggerSelectedAction();
            }}
          >
            <div className="flex min-w-0 items-center justify-between gap-3 px-4 py-3">
              <GitBranchSwitcher
                workspacePath={workspacePath}
                gitSummary={state.summary}
                dirtyFileCount={dirtyFileCount}
                onRefreshGit={onRefreshGit}
                className="min-w-0 px-0 pt-0"
                triggerClassName="h-7 max-w-64 justify-start rounded-lg px-1.5 text-foreground-subtle hover:bg-hover hover:text-foreground [&>span]:max-w-48"
                popoverSide="bottom"
                popoverClassName="w-80"
                branchListClassName="max-h-56"
                showFooterActions={false}
              />
              <div className="flex shrink-0 items-center gap-1.5 font-mono text-ui-base">
                <span className="text-diff-added">+{numberFormatter.format(displayAdded)}</span>
                <span className="text-diff-removed">-{numberFormatter.format(displayRemoved)}</span>
              </div>
            </div>

            <div className="min-h-36 px-4 pb-2">
              <label htmlFor={GIT_COMMIT_MESSAGE_TEXTAREA_ID} className="sr-only">
                {intl.formatMessage({
                  id: "git.actionMenu.commitDialog.messageLabel",
                })}
              </label>
              <div className="relative">
                <Textarea
                  ref={messageTextareaRef}
                  data-testid={TID_GIT_COMMIT_MESSAGE_INPUT}
                  id={GIT_COMMIT_MESSAGE_TEXTAREA_ID}
                  value={message}
                  disabled={actionPending}
                  placeholder={intl.formatMessage({
                    id: "git.actionMenu.commitDialog.messagePlaceholder",
                  })}
                  className="field-sizing-fixed min-h-28 rounded-none border-0 bg-transparent px-0 py-2 pr-8 text-ui-base font-medium text-foreground shadow-none placeholder:text-foreground-subtle focus-visible:border-transparent focus-visible:bg-transparent focus-visible:ring-0 md:text-ui-base"
                  onChange={(event) => {
                    onMessageChange(event.target.value);
                  }}
                />
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      data-testid={TID_GIT_COMMIT_GENERATE_BUTTON}
                      type="button"
                      variant="ghost"
                      size="icon-sm"
                      onClick={onGenerateMessage}
                      disabled={
                        actionPending ||
                        !hasSelectedChanges ||
                        (!hasIdentity && state.identity !== null)
                      }
                      aria-label={intl.formatMessage({
                        id: messageReady
                          ? "git.actionMenu.commitDialog.regenerate"
                          : "git.actionMenu.commitDialog.generate",
                      })}
                      className="absolute right-0 top-1.5 text-foreground-subtle hover:text-foreground"
                    >
                      {generationPending ? (
                        <LoaderIcon className="size-4 animate-spin" />
                      ) : (
                        <SparklesIcon className="size-4" />
                      )}
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent side="top" align="end" sideOffset={6}>
                    {intl.formatMessage({
                      id: messageReady
                        ? "git.actionMenu.commitDialog.regenerate"
                        : "git.actionMenu.commitDialog.generate",
                    })}
                  </TooltipContent>
                </Tooltip>
              </div>
            </div>

            {reviewError ? (
              <div className="space-y-2 px-4 py-2 text-ui-sm" role="alert">
                <p>{reviewError}</p>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  disabled={actionPending}
                  onClick={onManualFallback}
                >
                  {intl.formatMessage({ id: "git.review.manual" })}
                </Button>
              </div>
            ) : null}
            {review ? (
              <GitCommitReviewPanel
                review={review}
                position={reviewPosition}
                acknowledged={reviewAcknowledged}
                disabled={actionPending}
                onAcknowledge={onReviewAcknowledge}
                onManualFallback={onManualFallback}
              />
            ) : null}
            <div className="px-2.5 pb-2">
              <button
                type="button"
                role="checkbox"
                data-testid={TID_GIT_COMMIT_INCLUDE_UNSTAGED}
                aria-checked={includeUnstaged}
                disabled={actionPending || !hasUnstagedChanges}
                onClick={() => onIncludeUnstagedChange(!includeUnstaged)}
                className={cn(
                  "flex h-8 w-full items-center gap-2 rounded-lg px-2 text-left text-ui-base font-medium transition-colors",
                  actionPending || !hasUnstagedChanges
                    ? "cursor-default text-foreground-subtle"
                    : "cursor-pointer text-foreground hover:bg-menu-hover",
                )}
              >
                <span className="flex size-5 shrink-0 items-center justify-center">
                  <span
                    className={cn(
                      "flex size-4 items-center justify-center rounded-sm border",
                      includeUnstaged
                        ? "border-primary bg-primary text-primary-foreground"
                        : "border-border bg-background text-transparent",
                    )}
                  >
                    <CheckIcon className="size-3.5" />
                  </span>
                </span>
                <span className="min-w-0 flex-1 truncate">
                  {intl.formatMessage({
                    id: "git.actionMenu.commitDialog.includeUnstaged",
                  })}
                </span>
                <span className="shrink-0 text-ui-base font-normal text-foreground-subtle">
                  {intl.formatMessage(
                    {
                      id: "git.actionMenu.commitDialog.changesValue",
                    },
                    {
                      count: numberFormatter.format(fileCount),
                    },
                  )}
                </span>
              </button>
            </div>

            <div className="border-t border-border/50 px-2.5 py-2">
              {!hasIdentity ? (
                <div className="mb-1.5 flex items-start gap-2 rounded-lg bg-warning/10 px-3 py-2 text-ui-base text-warning">
                  <AlertCircleIcon className="mt-0.5 size-4 shrink-0" />
                  <p>
                    {intl.formatMessage({
                      id: "git.actionMenu.commitDialog.identityMissing",
                    })}
                  </p>
                </div>
              ) : null}

              {error ? <p className="px-3 py-1.5 text-ui-base text-destructive">{error}</p> : null}

              <Command
                data-testid={TID_GIT_COMMIT_ACTION_COMMAND}
                shouldFilter={false}
                loop
                tabIndex={0}
                value={selectedActionId}
                onValueChange={(nextValue) => {
                  if (isCommitDialogActionId(nextValue)) {
                    setSelectedActionId(nextValue);
                  }
                }}
                onKeyDown={handleActionCommandKeyDown}
                aria-label={intl.formatMessage({
                  id: "git.actionMenu.trigger.ariaLabel",
                })}
                className="rounded-none bg-transparent p-0 text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-input-border-focused"
              >
                <CommandList className="max-h-none scroll-py-1">
                  {commitActions.map((action) => (
                    <CommitCommandActionItem
                      key={action.id}
                      id={action.id}
                      icon={action.icon}
                      label={action.label}
                      shortcutLabel={
                        selectedActionId === action.id ? commitShortcutLabel : undefined
                      }
                      disabled={action.disabled}
                      loading={action.loading}
                      onSelect={action.onSelect}
                    />
                  ))}
                </CommandList>
              </Command>
            </div>
          </form>
        ) : (
          <div className="space-y-4 px-4 py-5">
            <p role="alert" className="break-words text-ui-base text-status-error">
              {error}
            </p>
            <div className="flex justify-end gap-2">
              <Button type="button" variant="ghost" onClick={() => onOpenChange(false)}>
                {intl.formatMessage({ id: "common.close" })}
              </Button>
              <Button type="button" onClick={onRetryLoad}>
                {intl.formatMessage({ id: "git.commitSummary.retry" })}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

interface GitPushDialogProps {
  open: boolean;
  gitSummary: GitRepositorySummary;
  currentBranchLabel: string;
  pushEnabled: boolean;
  error: string | null;
  mutationPending: boolean;
  onOpenChange: (nextOpen: boolean) => void;
  onSubmit: () => void;
}

function GitPushDialog({
  open,
  gitSummary,
  currentBranchLabel,
  pushEnabled,
  error,
  mutationPending,
  onOpenChange,
  onSubmit,
}: GitPushDialogProps) {
  const { intl, locale } = useLCodeIntl();
  const numberFormatter = new Intl.NumberFormat(locale);
  const [errorCopied, setErrorCopied] = useState(false);
  const descriptionId = gitSummary.trackingBranchName
    ? "git.actionMenu.pushDialog.description.tracked"
    : "git.actionMenu.pushDialog.description.untracked";

  const handleCopyError = useCallback(() => {
    if (!error) {
      return;
    }

    if (typeof navigator === "undefined" || !navigator.clipboard?.writeText) {
      toast(
        intl.formatMessage(
          { id: "git.actionMenu.pushDialog.error.copyFailed" },
          { error: "clipboard-unavailable" },
        ),
      );
      return;
    }

    void navigator.clipboard.writeText(error).then(
      () => {
        setErrorCopied(true);
        window.setTimeout(() => {
          setErrorCopied(false);
        }, 1500);
      },
      (copyError: unknown) => {
        const message = copyError instanceof Error ? copyError.message : String(copyError);
        toast(
          intl.formatMessage(
            { id: "git.actionMenu.pushDialog.error.copyFailed" },
            { error: message },
          ),
        );
      },
    );
  }, [error, intl]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        // 长错误或分支名会把推送框撑出横屏视口；整框纵向滚动，底部操作和原错误详情都保留。
        className="max-h-[85dvh] w-[calc(100%-2rem)] max-w-lg gap-0 overflow-y-auto overscroll-contain rounded-2xl p-0 [overflow-wrap:anywhere]"
      >
        <DialogHeader className="min-w-0 gap-2 px-6 py-5 pb-0">
          <DialogTitle className="pr-8 text-ui-xl font-medium text-foreground">
            {intl.formatMessage({ id: "git.actionMenu.pushDialog.title" })}
          </DialogTitle>
          <DialogDescription className="text-ui-base leading-6 text-foreground-subtle">
            {intl.formatMessage({ id: descriptionId })}
          </DialogDescription>
        </DialogHeader>

        <div className="min-w-0 space-y-5 px-6 py-6">
          {!error && (
            <div className="min-w-0 rounded-xl bg-background/30">
              <div className="flex min-w-0 flex-wrap items-start justify-between gap-2 p-4">
                <div className="text-ui-base font-medium text-foreground">
                  {intl.formatMessage({
                    id: "git.actionMenu.pushDialog.currentBranchLabel",
                  })}
                </div>
                <div className="flex min-w-0 max-w-full items-start gap-2 text-ui-base font-medium text-foreground">
                  <GitBranchIcon className="mt-0.5 size-4 shrink-0 text-foreground-subtle" />
                  <span className="min-w-0">{currentBranchLabel}</span>
                </div>
              </div>

              <div className="space-y-3 border-t border-border/50 p-4 text-ui-base">
                <div className="flex min-w-0 flex-wrap items-center justify-between gap-x-4 gap-y-1">
                  <div className="text-ui-base font-medium text-foreground">
                    {intl.formatMessage({
                      id: "git.actionMenu.pushDialog.upstreamLabel",
                    })}
                  </div>
                  <div className="min-w-0 max-w-full text-foreground-subtle">
                    {gitSummary.trackingBranchName
                      ? gitSummary.trackingBranchName
                      : intl.formatMessage({
                          id: "git.actionMenu.pushDialog.upstreamPending",
                        })}
                  </div>
                </div>
                <div className="flex min-w-0 flex-wrap items-center justify-between gap-x-4 gap-y-1">
                  <div className="text-ui-base font-medium text-foreground">
                    {intl.formatMessage({
                      id: "git.actionMenu.pushDialog.aheadBehindLabel",
                    })}
                  </div>
                  <div className="text-foreground-subtle">
                    {intl.formatMessage(
                      {
                        id: "git.actionMenu.pushDialog.aheadBehindValue",
                      },
                      {
                        ahead: numberFormatter.format(gitSummary.ahead),
                        behind: numberFormatter.format(gitSummary.behind),
                      },
                    )}
                  </div>
                </div>
                <div className="flex min-w-0 flex-wrap items-center justify-between gap-x-4 gap-y-1 border-t border-border/50 pt-3">
                  <div className="text-ui-base font-medium text-foreground">
                    {intl.formatMessage({
                      id: "git.actionMenu.pushDialog.pushLabel",
                    })}
                  </div>
                  <div className="flex min-w-0 max-w-full items-center gap-2 text-foreground-subtle">
                    <ArrowUpFromLine className="size-4 shrink-0" />
                    <span className="min-w-0">
                      {intl.formatMessage({
                        id: "git.actionMenu.pushDialog.pushValue",
                      })}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          )}

          {!pushEnabled ? (
            <div className="flex items-start gap-3 rounded-xl bg-warning/10 px-4 py-3 text-ui-base text-warning">
              <AlertCircleIcon className="mt-0.5 size-4 shrink-0" />
              <span>
                {intl.formatMessage({
                  id: "git.actionMenu.pushDialog.upToDate",
                })}
              </span>
            </div>
          ) : null}

          {error ? (
            <>
              <div className="flex items-start gap-3 rounded-xl bg-warning/10 px-4 py-3 text-ui-base text-warning">
                <AlertCircleIcon className="mt-0.5 size-4 shrink-0" />
                <span>
                  {intl.formatMessage({
                    id: "git.actionMenu.pushDialog.error.summary",
                  })}
                </span>
              </div>
              <div className="space-y-2">
                <div className="flex min-w-0 flex-wrap items-center justify-between gap-3">
                  <div className="text-ui-base font-medium text-foreground">
                    {intl.formatMessage({
                      id: "git.actionMenu.pushDialog.error.detailsLabel",
                    })}
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="h-auto min-h-7 max-w-full whitespace-normal px-2 text-ui-base text-foreground-subtle hover:text-foreground"
                    onClick={handleCopyError}
                  >
                    {intl.formatMessage({
                      id: errorCopied
                        ? "git.actionMenu.pushDialog.error.copy.copied"
                        : "git.actionMenu.pushDialog.error.copy",
                    })}
                  </Button>
                </div>
                <Textarea
                  // Textarea 默认带 field-sizing-content，长错误文本会按内容扩张并把弹窗横向撑爆。
                  // 这里改成固定尺寸模式，并允许长内容换行，保证错误详情始终被限制在弹窗宽度内。
                  className="field-sizing-fixed w-full max-w-full min-h-56 rounded-lg border-input-border bg-background/50 px-3 py-3 text-ui-base text-foreground whitespace-pre-wrap break-words placeholder:text-foreground-subtlest focus-visible:border-input-border-focused focus-visible:bg-input-focused focus-visible:ring-0 md:text-ui-base"
                  readOnly
                >
                  {error}
                </Textarea>
              </div>
            </>
          ) : null}

          <DialogFooter className="min-w-0 gap-2 pt-4 sm:flex-wrap">
            {error ? (
              <Button
                type="button"
                size="lg"
                onClick={() => onOpenChange(false)}
                disabled={mutationPending}
                className="h-auto min-h-10 min-w-0 max-w-full whitespace-normal px-5"
              >
                {intl.formatMessage({ id: "common.close" })}
              </Button>
            ) : (
              <>
                <Button
                  type="button"
                  variant="secondary"
                  size="lg"
                  onClick={() => onOpenChange(false)}
                  disabled={mutationPending}
                  className="h-auto min-h-10 min-w-0 max-w-full whitespace-normal px-5"
                >
                  {intl.formatMessage({ id: "common.cancel" })}
                </Button>
                <Button
                  type="button"
                  size="lg"
                  onClick={onSubmit}
                  disabled={mutationPending || !pushEnabled}
                  className="h-auto min-h-10 min-w-0 max-w-full whitespace-normal px-5"
                >
                  {mutationPending ? <LoaderIcon className="size-4 animate-spin" /> : null}
                  {intl.formatMessage({
                    id: "git.actionMenu.pushDialog.confirm",
                  })}
                </Button>
              </>
            )}
          </DialogFooter>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export function GitActionMenu({
  workspacePath,
  workspaceIdentity,
  gitSummary,
  activeTaskChangeSummary = null,
  commitMessageConversationContext = null,
  autoGeneratedCommitMessageDraft = null,
  dialogScopeKey,
  manualCommitMessageRequest = null,
  onManualCommitMessageSettled,
  onRefreshGit,
  className,
  triggerIconOnly = false,
  triggerLayout = "header",
}: GitActionMenuProps) {
  const { gitService } = useServices();
  const reviewUI = useGitCommitReview(workspaceIdentity?.trim() || workspacePath);
  const { intl, locale } = useLCodeIntl();
  const [commitDialogOpen, setCommitDialogOpen] = useState(false);
  const [commitDialogLoading, setCommitDialogLoading] = useState(false);
  const [commitDialogState, setCommitDialogState] = useState<GitCommitDialogState | null>(null);
  const [commitMessage, setCommitMessage] = useState("");
  const [commitError, setCommitError] = useState<string | null>(null);
  const [commitIncludeUnstaged, setCommitIncludeUnstaged] = useState(true);
  const [commitMessageGenerationPending, setCommitMessageGenerationPending] = useState(false);
  const [pushDialogOpen, setPushDialogOpen] = useState(false);
  const [pushError, setPushError] = useState<string | null>(null);
  const [mutationPending, setMutationPending] = useState(false);
  const scopeKey = dialogScopeKey ?? (workspaceIdentity?.trim() || workspacePath);
  const lifecycle = useMemo(() => new GitCommitDialogLifecycle(), [scopeKey]);
  const openedManualRequestRef = useRef<ManualGitCommitMessageRequest | null>(null);
  const handledManualRequestKeyRef = useRef<string | null>(null);
  const pendingManualRequestKeyRef = useRef<string | null>(null);
  const manualSettledCallbackRef = useRef(onManualCommitMessageSettled);
  manualSettledCallbackRef.current = onManualCommitMessageSettled;
  const settleManualRequest = useCallback((requestKey?: string) => {
    const key = pendingManualRequestKeyRef.current;
    if (requestKey && key !== requestKey) return;
    pendingManualRequestKeyRef.current = null;
    if (key) manualSettledCallbackRef.current?.(key);
  }, []);
  useEffect(() => {
    lifecycle.activate();
    return () => {
      if (lifecycle.current)
        logger.lifecycle.info("[GitActionMenu] 提交弹窗卸载", {
          scopeKey,
          attemptId: lifecycle.current.id,
          source: lifecycle.current.source,
          visible: lifecycle.current.visible,
        });
      lifecycle.dispose();
      settleManualRequest();
    };
  }, [lifecycle, scopeKey, settleManualRequest]);
  const reportCommitDialogVisible = useCallback(() => {
    const attempt = lifecycle.current;
    if (attempt && lifecycle.shown(attempt.id))
      logger.lifecycle.info("[GitActionMenu] 提交弹窗已显示", {
        scopeKey,
        attemptId: attempt.id,
        source: attempt.source,
        draftKey: attempt.draftKey,
      });
  }, [lifecycle, scopeKey]);

  const actionAvailable = canUseGitActionMenu(gitSummary);
  const currentBranchLabel = useMemo(
    () =>
      resolveGitBranchTriggerLabel({
        headRefType: gitSummary.headRefType,
        currentBranchName: gitSummary.branchName,
        detachedLabel: intl.formatMessage({ id: "git.head.detached" }),
        fallbackLabel: intl.formatMessage({ id: "git.branchSwitcher.label" }),
      }),
    [gitSummary.branchName, gitSummary.headRefType, intl],
  );
  const commitEnabled = gitSummary.isDirty;
  const pushEnabled = canPushGitBranch(gitSummary);
  const triggerPending = mutationPending || commitMessageGenerationPending || commitDialogLoading;
  const primaryActionId = useMemo(
    () =>
      resolveGitActionMenuPrimaryAction({
        actionAvailable,
        commitEnabled,
        pushEnabled,
      }),
    [actionAvailable, commitEnabled, pushEnabled],
  );
  const primaryActionDisabled = !actionAvailable || triggerPending || primaryActionId === null;
  const isStatusRowTrigger = triggerLayout === "status-row";

  useEffect(() => {
    // 顶部 commit 入口改成“始终展示、异常时置灰”后，
    // 这里记录低频可用性日志，方便继续区分是仓库探测失败，
    // 还是 UI 交互本身出现了禁用/启用状态不一致。
    logger.info("[GitActionMenu] 顶部 Git 操作入口可用性变化", {
      workspacePath,
      available: actionAvailable,
      primaryActionDisabled,
      primaryActionId,
      isGitAvailable: gitSummary.isGitAvailable,
      isRepository: gitSummary.isRepository,
      headRefType: gitSummary.headRefType,
      branchName: gitSummary.branchName,
      trackingBranchName: gitSummary.trackingBranchName,
      isDirty: gitSummary.isDirty,
    });
  }, [
    gitSummary.branchName,
    gitSummary.headRefType,
    gitSummary.isDirty,
    gitSummary.isGitAvailable,
    gitSummary.isRepository,
    gitSummary.trackingBranchName,
    actionAvailable,
    primaryActionId,
    primaryActionDisabled,
    workspacePath,
  ]);

  const closeCommitDialog = useCallback(
    (reason = "dismissed") => {
      const attempt = lifecycle.current;
      if (attempt)
        logger.lifecycle.info("[GitActionMenu] 提交弹窗关闭", {
          scopeKey,
          attemptId: attempt.id,
          source: attempt.source,
          visible: attempt.visible,
          reason,
        });
      lifecycle.close(reason === "dismissed");
      settleManualRequest();
      openedManualRequestRef.current = null;
      reviewUI.clear();
      setCommitDialogOpen(false);
      setCommitDialogLoading(false);
      setCommitDialogState(null);
      setCommitMessage("");
      setCommitError(null);
      setCommitIncludeUnstaged(true);
      setCommitMessageGenerationPending(false);
    },
    [lifecycle, scopeKey, settleManualRequest, reviewUI.clear],
  );

  const closePushDialog = useCallback(() => {
    setPushDialogOpen(false);
    setPushError(null);
  }, []);

  const openPushDialog = useCallback(() => {
    setPushError(null);
    setPushDialogOpen(true);
  }, []);

  const loadCommitDialogState = useCallback(
    async (options?: {
      resetMessage?: boolean;
      attemptId?: number;
    }): Promise<GitCommitDialogState | null> => {
      const attemptId = options?.attemptId ?? lifecycle.current?.id;
      if (attemptId === undefined || !lifecycle.isCurrent(attemptId)) return null;
      const manualRequest = openedManualRequestRef.current;
      setCommitDialogLoading(true);
      setCommitError(null);
      if (options?.resetMessage) {
        reviewUI.clear();
        setCommitMessage("");
      }

      try {
        const refreshResult = await gitService.refresh({
          workspacePath,
          includeIdentity: true,
        });
        if (!lifecycle.isCurrent(attemptId)) return null;
        const rawUnstagedFiles = buildGitBranchCommitPreviewFiles(refreshResult.unstagedChanges);
        const rawStagedFiles = buildGitBranchCommitPreviewFiles(refreshResult.stagedChanges);
        const mergedCurrentSessionFilePaths = mergeCurrentSessionFilePaths(
          // 草稿由生成时的文件范围锚定；task meta 可混入其它轮次，合并会造成假过期和空弹窗。
          manualRequest?.currentSessionFilePaths ??
            autoGeneratedCommitMessageDraft?.currentSessionFilePaths ??
            getCurrentSessionFilePaths(activeTaskChangeSummary),
        );
        const currentSessionFilePaths =
          mergedCurrentSessionFilePaths.length > 0 ? mergedCurrentSessionFilePaths : undefined;
        const unstagedFiles = filterCommitPreviewFilesByPaths({
          files: rawUnstagedFiles,
          currentSessionFilePaths,
          gitSummary: refreshResult.summary,
          workspacePath,
        });
        const stagedFiles = filterCommitPreviewFilesByPaths({
          files: rawStagedFiles,
          currentSessionFilePaths,
          gitSummary: refreshResult.summary,
          workspacePath,
        });
        const state: GitCommitDialogState = {
          summary: refreshResult.summary,
          activeTaskChangeSummary:
            manualRequest || autoGeneratedCommitMessageDraft ? null : activeTaskChangeSummary,
          ...(currentSessionFilePaths
            ? { currentSessionFilePaths: [...currentSessionFilePaths] }
            : {}),
          identity: refreshResult.identity,
          stagedFiles,
          unstagedFiles,
        };
        setCommitDialogState(state);
        setCommitIncludeUnstaged(unstagedFiles.length > 0);
        if (options?.resetMessage && autoGeneratedCommitMessageDraft && !manualRequest) {
          const currentFingerprint = buildGitChangesFingerprint({
            files: [...refreshResult.unstagedChanges, ...refreshResult.stagedChanges],
            currentSessionFilePaths: currentSessionFilePaths ?? [],
            gitSummary: refreshResult.summary,
            workspacePath,
          });
          const prefill = resolveAutoGitCommitMessagePrefill({
            draft: autoGeneratedCommitMessageDraft,
            currentFingerprint,
            staleMessage: intl.formatMessage({ id: "git.review.stale" }),
            unavailableMessage: intl.formatMessage({ id: "git.review.unavailable" }),
          });
          setCommitMessage(prefill.message);
          reviewUI.adopt(prefill.review, undefined, prefill.reviewError);
          if (prefill.reviewError) {
            logger.lifecycle.warn("[GitActionMenu] 自动提交草稿不可预填，显示错误", {
              workspacePath,
              draftKey: autoGeneratedCommitMessageDraft.key,
              stale: currentFingerprint !== autoGeneratedCommitMessageDraft.gitFingerprint,
              hasReview: Boolean(autoGeneratedCommitMessageDraft.review),
              messageLength: autoGeneratedCommitMessageDraft.message.length,
            });
          }
        }
        setCommitDialogLoading(false);
        logger.lifecycle.info("[GitActionMenu] 提交弹窗加载完成", {
          scopeKey,
          attemptId,
          fileCount: stagedFiles.length + unstagedFiles.length,
          source: lifecycle.current?.source,
        });
        return state;
      } catch (error: unknown) {
        if (!lifecycle.isCurrent(attemptId)) return null;
        const message = getErrorMessage(error);
        logger.lifecycle.warn("[GitActionMenu] 读取提交弹窗状态失败", {
          workspacePath,
          scopeKey,
          attemptId,
          error: message,
        });
        setCommitError(
          intl.formatMessage({ id: "git.commitSummary.loadFailed" }, { error: message }),
        );
        setCommitDialogState(null);
        setCommitDialogLoading(false);
        return null;
      }
    },
    [
      activeTaskChangeSummary,
      autoGeneratedCommitMessageDraft,
      lifecycle,
      scopeKey,
      gitService,
      intl,
      workspacePath,
      reviewUI.clear,
      reviewUI.adopt,
    ],
  );

  const openCommitDialog = useCallback(
    async (
      source: GitCommitDialogSource = "toolbar",
      request?: ManualGitCommitMessageRequest,
      draftKey?: string,
    ) => {
      const attemptId = lifecycle.begin(source, draftKey);
      openedManualRequestRef.current = request ?? null;
      logger.lifecycle.info("[GitActionMenu] 请求打开提交弹窗", {
        workspacePath,
        scopeKey,
        attemptId,
        source,
        draftKey,
        requestKey: request?.key,
      });
      setCommitDialogOpen(true);
      setCommitDialogState(null);
      setCommitMessage("");
      setCommitError(null);
      setCommitIncludeUnstaged(true);
      const state = await loadCommitDialogState({ resetMessage: true, attemptId });
      return { state, attemptId };
    },
    [loadCommitDialogState, lifecycle, scopeKey, workspacePath],
  );

  useEffect(() => {
    const draftKey = autoGeneratedCommitMessageDraft?.key ?? null;
    if (!actionAvailable || !draftKey) return;
    if (lifecycle.current) {
      lifecycle.ignoreDraft(draftKey);
      return;
    }
    // 延后一个微任务，让 StrictMode 的 effect replay 先失效，避免重复请求/空白弹窗。
    let scheduled = true;
    void Promise.resolve().then(() => {
      if (scheduled && lifecycle.canAutoOpen(draftKey))
        void openCommitDialog("automatic", undefined, draftKey);
    });
    return () => {
      scheduled = false;
    };
  }, [
    actionAvailable,
    autoGeneratedCommitMessageDraft?.key,
    commitDialogOpen,
    openCommitDialog,
    lifecycle,
  ]);

  const refreshCommitDialogAfterBranchChange = useCallback(() => {
    onRefreshGit();
    void loadCommitDialogState({ resetMessage: true });
  }, [loadCommitDialogState, onRefreshGit]);

  const generateCommitMessage = useCallback(
    async (
      state: GitCommitDialogState,
      includeUnstaged: boolean,
      attemptId: number,
    ): Promise<string> => {
      const ticket = reviewUI.begin();
      const files = getCommitDialogFiles(state, includeUnstaged);
      const currentSessionFilePaths = state.currentSessionFilePaths;
      const conversationContext =
        openedManualRequestRef.current?.conversationContext ?? commitMessageConversationContext;
      logger.lifecycle.info("[GitActionMenu] 开始生成提交消息", {
        workspacePath,
        attemptId,
        source: lifecycle.current?.source,
        branchName: gitSummary.branchName,
        selectedFileCount: files.length,
        currentSessionFileCount: currentSessionFilePaths?.length ?? 0,
        includeUnstaged,
        conversationMessageCount: conversationContext?.messages.length ?? 0,
      });

      const result = await gitService.generateCommitMessage({
        review: true,
        workspacePath,
        ...(workspaceIdentity ? { workspaceIdentity } : {}),
        locale,
        includeUnstaged,
        ...(currentSessionFilePaths ? { currentSessionFilePaths } : {}),
        ...(conversationContext ? { conversationContext } : {}),
      });

      if (
        !lifecycle.isCurrent(attemptId) ||
        !reviewUI.adopt(
          result.review,
          ticket,
          result.reviewError ??
            (!result.review ? intl.formatMessage({ id: "git.review.unavailable" }) : undefined),
        )
      )
        throw new Error("提交审核已取消或目标不再可用，请重新生成。");

      if (result.review && result.message.trim()) {
        logger.lifecycle.info("[GitActionMenu] 提交消息生成成功", {
          workspacePath,
          providerId: result.providerId,
          model: result.model,
        });
      } else {
        logger.lifecycle.warn("[GitActionMenu] 提交审核未生成，显示错误", {
          workspacePath,
          hasReview: Boolean(result.review),
          hasError: Boolean(result.reviewError),
        });
      }
      return result.message;
    },
    [
      commitMessageConversationContext,
      gitService,
      gitSummary.branchName,
      locale,
      workspaceIdentity,
      workspacePath,
      reviewUI.adopt,
      reviewUI.begin,
      intl,
      lifecycle,
    ],
  );

  const generateDialogMessage = useCallback(
    async (state: GitCommitDialogState, includeUnstaged: boolean, attemptId: number) => {
      if (!lifecycle.isCurrent(attemptId)) return;
      const stagePaths = getCommitDialogStagePaths(state, includeUnstaged);
      if (stagePaths.length === 0) {
        setCommitError(
          intl.formatMessage({
            id: "git.actionMenu.commitDialog.error.noChanges",
          }),
        );
        return;
      }

      setCommitError(null);
      setCommitMessageGenerationPending(true);

      try {
        const nextCommitMessage = await generateCommitMessage(state, includeUnstaged, attemptId);
        if (lifecycle.isCurrent(attemptId)) setCommitMessage(nextCommitMessage);
      } catch (error: unknown) {
        if (!lifecycle.isCurrent(attemptId)) return;
        const message = getErrorMessage(error);
        logger.lifecycle.warn("[GitActionMenu] 生成提交消息失败", {
          workspacePath,
          branchName: gitSummary.branchName,
          error: message,
        });
        const failure = intl.formatMessage({
          id: "git.actionMenu.commitDialog.error.generateFailed",
        });
        setCommitError(failure);
        reviewUI.adopt(undefined, undefined, failure);
      } finally {
        if (lifecycle.isCurrent(attemptId)) setCommitMessageGenerationPending(false);
      }
    },
    [generateCommitMessage, gitSummary.branchName, intl, workspacePath, lifecycle, reviewUI.adopt],
  );
  const handleGenerateCommitMessage = useCallback(async () => {
    const attemptId = lifecycle.current?.id;
    if (!commitDialogState || attemptId === undefined || commitMessageGenerationPending) return;
    await generateDialogMessage(commitDialogState, commitIncludeUnstaged, attemptId);
  }, [
    commitDialogState,
    commitIncludeUnstaged,
    commitMessageGenerationPending,
    generateDialogMessage,
    lifecycle,
  ]);

  useEffect(() => {
    const request = manualCommitMessageRequest;
    if (
      !request ||
      request.scopeKey !== scopeKey ||
      handledManualRequestKeyRef.current === request.key
    )
      return;
    let scheduled = true;
    void Promise.resolve().then(async () => {
      if (!scheduled) return;
      handledManualRequestKeyRef.current = request.key;
      if (lifecycle.current || !actionAvailable || !request.currentSessionFilePaths.length) {
        manualSettledCallbackRef.current?.(request.key);
        return;
      }
      pendingManualRequestKeyRef.current = request.key;
      try {
        const { state, attemptId } = await openCommitDialog("composer", request);
        if (state && lifecycle.isCurrent(attemptId))
          await generateDialogMessage(state, true, attemptId);
      } finally {
        settleManualRequest(request.key);
      }
    });
    return () => {
      scheduled = false;
    };
  }, [
    manualCommitMessageRequest,
    scopeKey,
    lifecycle,
    actionAvailable,
    openCommitDialog,
    generateDialogMessage,
    settleManualRequest,
  ]);

  const retryCommitDialogLoad = useCallback(async () => {
    const attemptId = lifecycle.current?.id;
    if (attemptId === undefined) return;
    const state = await loadCommitDialogState({ resetMessage: true, attemptId });
    if (state && openedManualRequestRef.current && lifecycle.isCurrent(attemptId)) {
      await generateDialogMessage(state, true, attemptId);
    }
  }, [lifecycle, loadCommitDialogState, generateDialogMessage]);

  const pushCurrentBranch = useCallback(
    async (options?: { showToast?: boolean }) => {
      const result = await gitService.push({ workspacePath });
      logger.info("[GitActionMenu] 推送更改成功", {
        workspacePath,
        branchName: result.branchName,
        trackingBranchName: result.trackingBranchName,
        remoteName: result.remoteName,
        setUpstream: result.setUpstream,
      });
      if (options?.showToast !== false) {
        toast(
          intl.formatMessage(
            { id: "git.actionMenu.pushDialog.toast.success" },
            {
              target:
                result.trackingBranchName?.trim() ||
                result.branchName?.trim() ||
                currentBranchLabel,
            },
          ),
        );
      }
      return result;
    },
    [currentBranchLabel, gitService, intl, workspacePath],
  );

  const handleCommitAction = useCallback(
    async (options?: { pushAfterCommit?: boolean }) => {
      if (!commitDialogState) {
        return;
      }

      if (!hasGitCommitIdentity(commitDialogState.identity)) {
        setCommitError(
          intl.formatMessage({
            id: "git.actionMenu.commitDialog.identityMissing",
          }),
        );
        return;
      }

      const includeUnstaged = commitIncludeUnstaged;
      const activeReview = reviewUI.review;
      const reviewGroup = reviewUI.group;
      if (!reviewUI.canSubmit) {
        setCommitError(reviewUI.error ?? intl.formatMessage({ id: "git.review.acknowledge" }));
        return;
      }
      if (activeReview && (!reviewGroup || !reviewUI.canSubmit)) {
        setCommitError(intl.formatMessage({ id: "git.review.acknowledge" }));
        return;
      }
      if (
        activeReview &&
        options?.pushAfterCommit &&
        reviewUI.position < activeReview.groups.length - 1
      )
        return;
      const stagePaths = getCommitDialogStagePaths(commitDialogState, includeUnstaged);
      const pathsToStage = includeUnstaged ? stagePaths : [];
      if (stagePaths.length === 0) {
        setCommitError(
          intl.formatMessage({
            id: "git.actionMenu.commitDialog.error.noChanges",
          }),
        );
        return;
      }

      const nextCommitMessage = commitMessage.trim();
      if (!nextCommitMessage) {
        const attemptId = lifecycle.current?.id;
        if (attemptId !== undefined)
          await generateDialogMessage(commitDialogState, includeUnstaged, attemptId);
        // 新生成的冻结候选必须先展示给用户，不能在同一次点击中直接提交。
        return;
      }

      setCommitError(null);
      setMutationPending(true);
      let committed = false;

      try {
        logger.info("[GitActionMenu] 开始提交当前更改", {
          workspacePath,
          branchName: gitSummary.branchName,
          selectedPathCount: stagePaths.length,
          stagedPathCount: pathsToStage.length,
          includeUnstaged,
          pushAfterCommit: Boolean(options?.pushAfterCommit),
        });
        if (!activeReview && pathsToStage.length > 0) {
          await gitService.stagePaths({
            workspacePath,
            paths: pathsToStage,
          });
        }
        const result = await gitService.commit({
          workspacePath,
          ...(workspaceIdentity ? { workspaceIdentity } : {}),
          message: nextCommitMessage,
          ...(activeReview && reviewGroup
            ? {
                review: {
                  id: activeReview.id,
                  groupId: reviewGroup.id,
                  acknowledged: reviewUI.acknowledged,
                },
              }
            : { paths: stagePaths, stagedOnly: !includeUnstaged }),
        });
        committed = true;
        const nextGroup = activeReview?.groups[reviewUI.position + 1];
        if (activeReview) {
          // 服务端先记录成功组；UI 仅推进显示游标。推送失败也不能回退到已提交候选。
          reviewUI.advance(activeReview.id, reviewGroup!.id);
          setCommitMessage(nextGroup?.message ?? "");
        }
        if (result.warning) {
          setCommitError(result.warning);
          onRefreshGit();
          return;
        }
        if (nextGroup) {
          toast(intl.formatMessage({ id: "git.actionMenu.commitDialog.toast.success" }));
          onRefreshGit();
          return;
        }

        if (options?.pushAfterCommit) {
          await pushCurrentBranch({ showToast: false });
        }

        logger.info("[GitActionMenu] 提交当前更改成功", {
          workspacePath,
          branchName: gitSummary.branchName,
          pushAfterCommit: Boolean(options?.pushAfterCommit),
        });
        toast(
          intl.formatMessage({
            id: options?.pushAfterCommit
              ? "git.actionMenu.commitDialog.toast.commitAndPushSuccess"
              : "git.actionMenu.commitDialog.toast.success",
          }),
        );
        closeCommitDialog("submitted");
        onRefreshGit();
      } catch (error: unknown) {
        const message = getErrorMessage(error);
        logger.warn("[GitActionMenu] 提交当前更改失败", {
          workspacePath,
          error: message,
          committed,
          pushAfterCommit: Boolean(options?.pushAfterCommit),
        });
        setCommitError(
          intl.formatMessage(
            {
              id:
                committed && options?.pushAfterCommit
                  ? "git.actionMenu.commitDialog.error.pushAfterCommitFailed"
                  : "git.actionMenu.commitDialog.error.requestFailed",
            },
            { error: message },
          ),
        );
        if (committed) {
          onRefreshGit();
        }
      } finally {
        setMutationPending(false);
      }
    },
    [
      closeCommitDialog,
      commitIncludeUnstaged,
      commitDialogState,
      commitMessage,
      generateDialogMessage,
      lifecycle,
      gitService,
      gitSummary.branchName,
      intl,
      onRefreshGit,
      pushCurrentBranch,
      workspacePath,
      workspaceIdentity,
      reviewUI.review,
      reviewUI.group,
      reviewUI.position,
      reviewUI.acknowledged,
      reviewUI.canSubmit,
      reviewUI.error,
      reviewUI.advance,
    ],
  );

  const handleCommitSubmit = useCallback(async () => {
    await handleCommitAction();
  }, [handleCommitAction]);

  const handleCommitAndPushSubmit = useCallback(async () => {
    await handleCommitAction({ pushAfterCommit: true });
  }, [handleCommitAction]);

  const handlePushSubmit = useCallback(async () => {
    if (!pushEnabled) {
      return;
    }

    setMutationPending(true);
    setPushError(null);

    try {
      await pushCurrentBranch();
      closePushDialog();
      onRefreshGit();
    } catch (error: unknown) {
      const message = getErrorMessage(error);
      logger.warn("[GitActionMenu] 推送更改失败", {
        workspacePath,
        error: message,
      });
      setPushError(
        intl.formatMessage(
          { id: "git.actionMenu.pushDialog.error.requestFailed" },
          { error: message },
        ),
      );
    } finally {
      setMutationPending(false);
    }
  }, [closePushDialog, intl, onRefreshGit, pushCurrentBranch, pushEnabled, workspacePath]);

  const handlePrimaryAction = useCallback(() => {
    if (primaryActionDisabled) {
      return;
    }

    runUserAction({
      input: { featureId: "workbench.git", action: "open", trigger: "button" },
      operation: () => {
        if (primaryActionId === "push") {
          openPushDialog();
          return;
        }
        void openCommitDialog();
      },
      completed: { resultSource: "local_commit" },
      failureStage: "git_action_open",
    });
  }, [openCommitDialog, openPushDialog, primaryActionId, primaryActionDisabled]);

  const handleStatusRowContainerClick = useCallback(() => {
    handlePrimaryAction();
  }, [handlePrimaryAction]);

  return (
    <>
      <div
        onClick={isStatusRowTrigger && !triggerIconOnly ? handleStatusRowContainerClick : undefined}
        className={cn(
          // macOS/Windows 小窗口下，顶部 Git 主按钮的中文文案会和分支入口、窗口控制区挤在同一行。
          // 在 header 容器变窄时只隐藏主按钮文字，保留图标入口，避免丢失核心 Git 操作。
          // transition-all 会把 scrollbar-color 等非合成属性也启动动画，
          // 进而触发整页 UpdateLayoutTree；Git 入口只需要颜色反馈，不动画尺寸和滚动条属性。
          "flex h-7 items-center overflow-hidden rounded-lg border border-border bg-input transition-colors hover:border-border-hover @max-[560px]/workspace-header:w-7 @max-[560px]/workspace-header:justify-center",
          triggerIconOnly && "w-7 justify-center",
          isStatusRowTrigger &&
            "h-8 w-full justify-start rounded-lg border-0 bg-transparent hover:border-transparent hover:bg-hover @max-[560px]/workspace-header:w-full @max-[560px]/workspace-header:justify-start",
          className,
        )}
      >
        <Button
          data-testid={TID_GIT_ACTION_TRIGGER}
          type="button"
          variant="ghost"
          size="default"
          disabled={primaryActionDisabled}
          aria-label={intl.formatMessage({
            id: "git.actionMenu.trigger.ariaLabel",
          })}
          className={cn(
            "h-7 rounded-lg border-0 gap-1 px-1.5 @max-[560px]/workspace-header:w-7 @max-[560px]/workspace-header:px-0 @max-[560px]/workspace-header:[&>span]:hidden",
            triggerIconOnly && "w-7 px-0 [&>span]:hidden",
            isStatusRowTrigger &&
              "h-8 min-w-0 w-full justify-start gap-2 px-2 text-left text-ui-base hover:bg-transparent hover:text-foreground @max-[560px]/workspace-header:w-auto @max-[560px]/workspace-header:[&>span]:inline",
          )}
          onClick={isStatusRowTrigger && !triggerIconOnly ? undefined : handlePrimaryAction}
        >
          {/* 主按钮进入 pending 时直接替换左侧动作图标，避免在紧凑头部里额外追加 loading 图标把按钮挤宽。*/}
          {triggerPending ? (
            <LoaderIcon className="size-4 animate-spin text-foreground-subtle" />
          ) : primaryActionId === "push" ? (
            <ArrowUpFromLine className="size-4 text-foreground" />
          ) : (
            <GitCommitIcon className="size-4 text-foreground" />
          )}
          <span className={cn(isStatusRowTrigger && "min-w-0 truncate")}>
            {intl.formatMessage({ id: "git.actionMenu.trigger" })}
          </span>
        </Button>
      </div>

      <GitCommitDialog
        onVisible={reportCommitDialogVisible}
        onRetryLoad={() => {
          void retryCommitDialogLoad();
        }}
        reviewError={reviewUI.error}
        review={reviewUI.review}
        reviewPosition={reviewUI.position}
        reviewAcknowledged={reviewUI.acknowledged}
        reviewCanSubmit={reviewUI.canSubmit}
        onReviewAcknowledge={reviewUI.acknowledge}
        onManualFallback={reviewUI.clear}
        open={commitDialogOpen}
        loading={commitDialogLoading}
        state={commitDialogState}
        workspacePath={workspacePath}
        message={commitMessage}
        error={commitError}
        mutationPending={mutationPending}
        generationPending={commitMessageGenerationPending}
        includeUnstaged={commitIncludeUnstaged}
        pushEnabled={pushEnabled}
        onRefreshGit={refreshCommitDialogAfterBranchChange}
        onOpenChange={(nextOpen) => {
          if (!nextOpen) {
            closeCommitDialog();
          }
        }}
        onMessageChange={setCommitMessage}
        onIncludeUnstagedChange={(value) => {
          reviewUI.clear();
          setCommitIncludeUnstaged(value);
          setCommitMessage("");
        }}
        onGenerateMessage={() => {
          void handleGenerateCommitMessage();
        }}
        onSubmit={() => {
          void handleCommitSubmit();
        }}
        onSubmitAndPush={() => {
          void handleCommitAndPushSubmit();
        }}
        onPushOnly={() => {
          closeCommitDialog("push");
          openPushDialog();
        }}
      />

      <GitPushDialog
        open={pushDialogOpen}
        gitSummary={gitSummary}
        currentBranchLabel={currentBranchLabel}
        pushEnabled={pushEnabled}
        error={pushError}
        mutationPending={mutationPending}
        onOpenChange={(nextOpen) => {
          if (!nextOpen) {
            closePushDialog();
          }
        }}
        onSubmit={() => {
          void handlePushSubmit();
        }}
      />
    </>
  );
}
