/* eslint-disable max-lines -- GitActionMenu 协调本端审核窗口与发布执行；草稿已接受状态归 Host，纯计划与显示组件按边界拆分。 */
import type { ReactNode } from "react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type {
  GitCommitMessageConversationContext,
  GitCommitRequest,
  GitCommitResult,
  GitRemoteInfo,
  GitRepositorySummary,
  GitTagInfo,
  GitUnsupportedTagInfo,
  LCodeTaskChangeSummary,
} from "@lcode/shared";
import { ArrowUpFromLine, GitCommitIcon, LoaderIcon } from "lucide-react";
import { cn } from "@/components/lib/utils.js";
import { Button } from "@/components/ui/button.js";
import { toast } from "@/components/ui/toast.js";
import { buildGitBranchCommitPreviewFiles } from "@/git-branch-switcher/display.js";
import { hasGitCommitIdentity } from "@/git-branch-switcher/switchAssist.js";
import {
  canUseGitActionMenu,
  canPushGitBranch,
  resolveGitActionMenuPrimaryAction,
} from "@/git-action-menu/display.js";
import {
  buildGitChangesFingerprint,
  filterCommitPreviewFilesByPaths,
  getCurrentSessionFilePaths,
} from "@/git-action-menu/currentSessionFileScope.js";
import {
  mergeCurrentSessionFilePaths,
  resolveAutoGitCommitMessagePrefill,
  selectGitCommitMessageForScope,
  type AutoGeneratedGitCommitMessageDraft,
  type ManualGitCommitMessageRequest,
} from "@/git-action-menu/autoCommitMessage.js";
import {
  GitCommitDialogLifecycle,
  type GitCommitDialogSource,
} from "@/git-action-menu/gitCommitDialogLifecycle.js";
import { GitCommitDialog } from "@/git-action-menu/GitCommitDialog.js";
import {
  getCommitDialogFiles,
  getCommitDialogStagePaths,
  type GitCommitDialogState,
} from "@/git-action-menu/commitDialogModel.js";
import { commitDraftScopeKey } from "@/git-action-menu/commitDraft.js";
import {
  createPublishOptions,
  freezePublishPlan,
  validatePublishOptions,
  type PublishPlan,
} from "@/git-action-menu/publishModel.js";
import {
  executePublishPlan,
  retryPublishStep,
  type PublishRun,
} from "@/git-action-menu/publishExecution.js";
import {
  applyPublishPreset,
  parsePublishPresets,
  publishPresetStorageKey,
  serializePublishPresets,
  type PublishPreset,
} from "@/git-action-menu/publishPresets.js";
import { CommitAndMergeControl } from "@/worktree/CommitAndMergeControl.js";
import { advanceCommitReviewPosition } from "@/git-action-menu/commitReviewModel.js";
import { useProjectExecutionPolicy } from "@/hooks/useProjectExecutionPolicy.js";
import { useServices } from "@/hooks/useServices.js";
import { useOptionalPlatform } from "@/hooks/usePlatform.js";
import { useGitCommitReview } from "@/hooks/useGitCommitReview.js";
import { useGitCommitDraft } from "@/hooks/useGitCommitDraft.js";
import { useReviewDiffNavigation } from "@/hooks/useReviewDiffNavigation.js";
import { useReviewWorkspaceState } from "@/hooks/useReviewWorkspaceState.js";
import { ReviewWorkspaceSyncStatus } from "@/git-action-menu/ReviewWorkspaceSyncStatus.js";
import { useSynchronizedCommitReview } from "@/hooks/useSynchronizedCommitReview.js";
import { useLCodeIntl } from "@/i18n/IntlProvider.js";
import { getErrorMessage } from "@/lib/errorMessage.js";
import { getCheckoutOperationErrorMessage } from "@/lib/checkoutOperationError.js";
import { runUserAction } from "@/lib/userActionTelemetry.js";
import { logger } from "@/logger.js";

interface GitActionMenuProps {
  workspacePath: string;
  workspaceIdentity?: string;
  workspaceRemoteSessionId?: string;
  originWorkspacePath?: string;
  originWorkspaceIdentity?: string;
  executionSessionId?: string;
  reviewEpoch?: string;
  executionBindingId?: string;
  gitSummary: GitRepositorySummary;
  activeTaskChangeSummary?: LCodeTaskChangeSummary | null;
  commitMessageConversationContext?: GitCommitMessageConversationContext | null;
  autoGeneratedCommitMessageDraft?: AutoGeneratedGitCommitMessageDraft | null;
  dialogScopeKey?: string;
  manualCommitMessageRequest?: ManualGitCommitMessageRequest | null;
  onManualCommitMessageSettled?: (key: string) => void;
  onRefreshGit: () => void;
  className?: string;
  triggerIconOnly?: boolean;
  triggerLayout?: "header" | "status-row";
}

export function GitActionMenu({
  workspacePath,
  workspaceIdentity,
  workspaceRemoteSessionId,
  originWorkspacePath,
  originWorkspaceIdentity,
  executionSessionId,
  reviewEpoch,
  executionBindingId,
  gitSummary,
  activeTaskChangeSummary = null,
  commitMessageConversationContext = null,
  autoGeneratedCommitMessageDraft: suppliedAutoDraft = null,
  dialogScopeKey,
  manualCommitMessageRequest = null,
  onManualCommitMessageSettled,
  onRefreshGit,
  className,
  triggerIconOnly = false,
  triggerLayout = "header",
}: GitActionMenuProps) {
  const { gitService } = useServices();
  const { policy: executionPolicy } = useProjectExecutionPolicy(
    originWorkspacePath ?? workspacePath,
    originWorkspaceIdentity ?? workspaceIdentity,
  );
  const platform = useOptionalPlatform();
  const { intl, locale } = useLCodeIntl();
  // 项目默认只影响新会话；已有会话的文案必须跟随 CLI 已保存的实际执行绑定。
  const executionMode = executionBindingId ? "worktree" : "local";
  const workflowTitle = intl.formatMessage({ id: `git.commitWorkflow.${executionMode}.title` });
  const scopeKey = dialogScopeKey ?? (workspaceIdentity?.trim() || workspacePath);
  const autoGeneratedCommitMessageDraft = selectGitCommitMessageForScope(
    suppliedAutoDraft,
    scopeKey,
  );
  const draftScope = commitDraftScopeKey(workspacePath, workspaceIdentity, scopeKey);
  const workspaceReview = useReviewWorkspaceState(
    originWorkspacePath ?? workspacePath,
    originWorkspaceIdentity ?? workspaceIdentity,
    reviewEpoch
      ? JSON.stringify([executionSessionId ?? scopeKey, reviewEpoch])
      : (executionSessionId ?? scopeKey),
  );
  const draftUI = useGitCommitDraft(workspaceReview);
  const reviewUI = useGitCommitReview(draftScope);
  const lifecycle = useMemo(() => new GitCommitDialogLifecycle(), [draftScope]);
  const currentScopeRef = useRef(draftScope);
  currentScopeRef.current = draftScope;
  const viewRevisionRef = useRef(0);
  const loadTicketRef = useRef(0);
  const catalogTicketRef = useRef(0);
  const busyRef = useRef(false);
  const [commitDialogOpen, setCommitDialogOpen] = useState(false);
  const [commitDialogLoading, setCommitDialogLoading] = useState(false);
  const [commitDialogState, setCommitDialogState] = useState<GitCommitDialogState | null>(null);
  const [commitError, setCommitError] = useState<string | null>(null);
  const commitIncludeUnstaged = workspaceReview.data.includeUnstaged;
  const setCommitIncludeUnstaged = useCallback(
    (value: boolean) => workspaceReview.set("includeUnstaged", value),
    [workspaceReview.set],
  );
  const [generationPending, setGenerationPending] = useState(false);
  const [mutationPending, setMutationPending] = useState(false);
  const browsePosition = workspaceReview.data.browsePosition;
  const setBrowsePosition = useCallback(
    (value: number) => workspaceReview.set("browsePosition", value),
    [workspaceReview.set],
  );
  const excludedFiles = workspaceReview.data.excludedFiles;
  const setExcludedFiles = useCallback(
    (value: import("react").SetStateAction<string[]>) =>
      workspaceReview.set("excludedFiles", value),
    [workspaceReview.set],
  );
  const [publishExpanded, setPublishExpanded] = useState(false);
  const [publishOptions, setPublishOptions] = useState(createPublishOptions);
  const [publishCatalog, setPublishCatalog] = useState<{
    remotes: GitRemoteInfo[];
    tags: GitTagInfo[];
    unsupportedTags: GitUnsupportedTagInfo[];
    loaded: boolean;
    loading: boolean;
    error: string | null;
  }>({ remotes: [], tags: [], unsupportedTags: [], loaded: false, loading: false, error: null });
  const [publishPlan, setPublishPlan] = useState<PublishPlan | null>(null);
  const [publishRun, setPublishRun] = useState<PublishRun | null>(null);
  const [presets, setPresets] = useState<PublishPreset[]>([]);
  const [presetName, setPresetName] = useState("");
  const [selectedPreset, setSelectedPreset] = useState("");
  const presetKey = publishPresetStorageKey(workspacePath, workspaceIdentity);
  const repositoryRequest = useMemo(
    () => ({ workspacePath, ...(workspaceIdentity ? { workspaceIdentity } : {}) }),
    [workspacePath, workspaceIdentity],
  );
  const openedManualRequestRef = useRef<ManualGitCommitMessageRequest | null>(null);
  const handledManualRequestKeyRef = useRef<string | null>(null);
  const pendingManualRequestKeyRef = useRef<string | null>(null);
  const manualSettledCallbackRef = useRef(onManualCommitMessageSettled);
  manualSettledCallbackRef.current = onManualCommitMessageSettled;
  const settleManualRequest = useCallback((requestKey?: string) => {
    const key = pendingManualRequestKeyRef.current;
    if (requestKey && key !== requestKey) return;
    pendingManualRequestKeyRef.current = null;
    if (key) manualSettledCallbackRef.current?.(key);
  }, []);
  const isCurrent = useCallback(
    (attemptId: number, revision?: number) =>
      currentScopeRef.current === draftScope &&
      lifecycle.isCurrent(attemptId) &&
      (revision === undefined || revision === viewRevisionRef.current),
    [draftScope, lifecycle],
  );
  useSynchronizedCommitReview(workspaceReview, reviewUI, workspacePath, workspaceIdentity, () => {
    reviewUI.acknowledge(false);
    if (!mutationPending) setPublishPlan(null);
  });

  useEffect(() => {
    lifecycle.activate();
    busyRef.current = false;
    viewRevisionRef.current++;
    setCommitDialogOpen(false);
    setCommitDialogState(null);
    setCommitDialogLoading(false);
    setGenerationPending(false);
    setMutationPending(false);
    setPublishPlan(null);
    setPublishRun(null);
    setPublishOptions(createPublishOptions());
    setPublishExpanded(false);
    return () => {
      lifecycle.dispose();
      settleManualRequest();
    };
  }, [lifecycle, settleManualRequest]);

  const actionAvailable = canUseGitActionMenu(gitSummary);
  const primaryActionId = resolveGitActionMenuPrimaryAction({
    actionAvailable,
    commitEnabled: gitSummary.isDirty,
    pushEnabled: canPushGitBranch(gitSummary),
  });
  const triggerPending = mutationPending || generationPending || commitDialogLoading;
  const primaryActionDisabled =
    !actionAvailable ||
    (triggerPending && !lifecycle.current) ||
    workspaceReview.status === "loading";
  const isStatusRowTrigger = triggerLayout === "status-row";
  const reportCommitDialogVisible = useCallback(() => {
    const attempt = lifecycle.current;
    if (attempt && isCurrent(attempt.id) && lifecycle.shown(attempt.id))
      logger.lifecycle.info("[GitActionMenu] 提交弹窗已显示", {
        scopeKey,
        attemptId: attempt.id,
        source: attempt.source,
      });
  }, [isCurrent, lifecycle, scopeKey]);

  const closeCommitDialog = useCallback(
    (reason = "dismissed") => {
      const attempt = lifecycle.current;
      if (attempt)
        logger.lifecycle.info("[GitActionMenu] 提交弹窗关闭", {
          scopeKey,
          attemptId: attempt.id,
          reason,
        });
      // 关闭仅隐藏展示，不能丢弃冻结审核或中断已接受的 Git 操作；scope 清理才失效 attempt。
      settleManualRequest();
      setCommitDialogOpen(false);
    },
    [lifecycle, scopeKey, settleManualRequest],
  );

  const invalidateReview = useCallback(() => {
    viewRevisionRef.current++;
    reviewUI.clear();
    workspaceReview.patch({
      sourceReview: null,
      browsePosition: 0,
      draft: { ...draftUI.read(), requiresRegeneration: true },
    });

    setPublishPlan(null);
    setCommitError(null);
    setGenerationPending(false);
    // 范围变化会拒绝同轮迟到的目录读取；同时解除它的 pending，保留显式重读入口。
    setPublishCatalog((previous) =>
      previous.loading ? { ...previous, loading: false, loaded: false } : previous,
    );
  }, [reviewUI.clear, draftUI.read, workspaceReview.patch]);

  const diffNavigation = useReviewDiffNavigation(
    draftScope,
    () => setCommitDialogOpen(false),
    () => setCommitDialogOpen(true),
    {
      disabled:
        ["loading", "error", "conflict"].includes(workspaceReview.status) ||
        triggerPending ||
        Boolean(publishPlan || publishRun) ||
        Boolean(reviewUI.review && browsePosition !== reviewUI.position),
      excludedFiles,
      exclude: (paths) => {
        if (busyRef.current || publishPlan || publishRun) return;
        invalidateReview();
        setExcludedFiles((previous) => [...new Set([...previous, ...paths])]);
      },
      restore: (paths) => {
        if (busyRef.current || publishPlan || publishRun) return;
        invalidateReview();
        const restored = new Set(paths);
        setExcludedFiles((previous) => previous.filter((path) => !restored.has(path)));
      },
    },
  );
  const openReviewFiles = (all = false) => {
    const frozen = all ? undefined : reviewUI.review?.groups[browsePosition]?.files;
    const unstaged = new Set(commitDialogState?.unstagedFiles.map((file) => file.repoRelativePath));
    const files =
      frozen ??
      (commitDialogState
        ? [
            ...new Map(
              getCommitDialogFiles(commitDialogState, true).map((file) => [
                file.repoRelativePath,
                { path: file.repoRelativePath, staged: !unstaged.has(file.repoRelativePath) },
              ]),
            ).values(),
          ]
        : []);
    diffNavigation.openDiff({
      type: "patch",
      title: intl.formatMessage({ id: "git.review.fileScope" }),
      patch: "",
      reviewFiles: files,
      workspacePath,
      workspaceIdentity,
      workspaceRemoteSessionId,
    });
  };

  const loadCommitDialogState = useCallback(
    async (options?: {
      attemptId?: number;
      allowPrefill?: boolean;
      resetInclude?: boolean;
      preferSharedScope?: boolean;
    }): Promise<GitCommitDialogState | null> => {
      const attemptId = options?.attemptId ?? lifecycle.current?.id;
      if (attemptId === undefined || !isCurrent(attemptId)) return null;
      const revision = viewRevisionRef.current;
      const ticket = ++loadTicketRef.current;
      const current = () => isCurrent(attemptId, revision) && ticket === loadTicketRef.current;
      const manualRequest = openedManualRequestRef.current;
      setCommitDialogLoading(true);
      setCommitError(null);
      try {
        const refreshResult = await gitService.refresh({
          ...repositoryRequest,
          includeIdentity: true,
        });
        if (!current()) return null;
        const mergedPaths = mergeCurrentSessionFilePaths(
          options?.preferSharedScope
            ? (workspaceReview.read().data.selectedPaths ?? [])
            : (manualRequest?.currentSessionFilePaths ??
                autoGeneratedCommitMessageDraft?.currentSessionFilePaths ??
                workspaceReview.read().data.selectedPaths ??
                getCurrentSessionFilePaths(activeTaskChangeSummary)),
        );
        const explicitScope = options?.preferSharedScope
          ? workspaceReview.read().data.selectedPaths !== null
          : manualRequest?.currentSessionFilePaths !== undefined ||
            autoGeneratedCommitMessageDraft?.currentSessionFilePaths !== undefined ||
            workspaceReview.read().data.selectedPaths !== null;
        const currentSessionFilePaths =
          explicitScope || mergedPaths.length ? mergedPaths : undefined;
        const filter = (files: ReturnType<typeof buildGitBranchCommitPreviewFiles>) =>
          filterCommitPreviewFilesByPaths({
            files,
            currentSessionFilePaths,
            gitSummary: refreshResult.summary,
            workspacePath,
          });
        const state: GitCommitDialogState = {
          summary: refreshResult.summary,
          identity: refreshResult.identity,
          activeTaskChangeSummary:
            manualRequest || autoGeneratedCommitMessageDraft ? null : activeTaskChangeSummary,
          ...(currentSessionFilePaths ? { currentSessionFilePaths } : {}),
          unstagedFiles: filter(buildGitBranchCommitPreviewFiles(refreshResult.unstagedChanges)),
          stagedFiles: filter(buildGitBranchCommitPreviewFiles(refreshResult.stagedChanges)),
        };
        setCommitDialogState(state);
        if (
          options?.resetInclude &&
          workspaceReview.read().snapshot.fieldRevisions.includeUnstaged === 0
        )
          setCommitIncludeUnstaged(state.unstagedFiles.length > 0);
        if (
          options?.allowPrefill &&
          autoGeneratedCommitMessageDraft &&
          !manualRequest &&
          !draftUI.read().edited &&
          !draftUI.read().message
        ) {
          const currentFingerprint = buildGitChangesFingerprint({
            files: [...refreshResult.unstagedChanges, ...refreshResult.stagedChanges],
            currentSessionFilePaths: currentSessionFilePaths ?? [],
            gitSummary: refreshResult.summary,
            workspacePath,
          });
          const prefill = resolveAutoGitCommitMessagePrefill({
            draft: autoGeneratedCommitMessageDraft,
            scopeKey,
            currentFingerprint,
            staleMessage: intl.formatMessage({ id: "git.review.stale" }),
            unavailableMessage: intl.formatMessage({ id: "git.review.unavailable" }),
          });
          reviewUI.adopt(prefill.review, undefined, prefill.reviewError);
          workspaceReview.patch({
            draft: {
              message: prefill.message,
              previousMessage: null,
              edited: false,
              requiresRegeneration: false,
            },
            sourceReview: prefill.review ? { id: prefill.review.id } : null,
            browsePosition: 0,
            selectedPaths: currentSessionFilePaths ?? null,
          });
          if (prefill.reviewError)
            logger.lifecycle.warn("[GitActionMenu] 自动提交审核不可用，纪要按有效指纹独立预填", {
              workspacePath,
              draftKey: autoGeneratedCommitMessageDraft.key,
            });
        }
        return state;
      } catch (error) {
        if (!current()) return null;
        setCommitError(
          intl.formatMessage(
            { id: "git.commitSummary.loadFailed" },
            {
              error: getCheckoutOperationErrorMessage(
                error,
                intl.formatMessage({ id: "git.commitWorkflow.directoryBusy" }),
              ),
            },
          ),
        );
        setCommitDialogState(null);
        return null;
      } finally {
        if (current()) setCommitDialogLoading(false);
      }
    },
    [
      lifecycle,
      isCurrent,
      gitService,
      repositoryRequest,
      activeTaskChangeSummary,
      autoGeneratedCommitMessageDraft,
      scopeKey,
      workspacePath,
      draftUI.read,
      draftUI.prefill,
      reviewUI.adopt,
      intl,
    ],
  );

  const appliedScopeRevision = useRef({ scope: draftScope, revision: 0 });
  const selectedScopeRevision = workspaceReview.snapshot.fieldRevisions.selectedPaths;
  useEffect(() => {
    if (
      !commitDialogOpen ||
      generationPending ||
      workspaceReview.read().status !== "ready" ||
      !lifecycle.current ||
      selectedScopeRevision === 0
    )
      return;
    if (
      appliedScopeRevision.current.scope === draftScope &&
      appliedScopeRevision.current.revision === selectedScopeRevision
    )
      return;
    appliedScopeRevision.current = { scope: draftScope, revision: selectedScopeRevision };
    void loadCommitDialogState({ attemptId: lifecycle.current.id, preferSharedScope: true });
  }, [
    commitDialogOpen,
    generationPending,
    workspaceReview.status === "ready",
    selectedScopeRevision,
    draftScope,
    lifecycle,
    workspaceReview.read,
    loadCommitDialogState,
  ]);

  const readPresets = useCallback(() => {
    try {
      setPresets(parsePublishPresets(localStorage.getItem(presetKey)));
    } catch {
      setPresets([]);
    }
    setPresetName("");
    setSelectedPreset("");
  }, [presetKey]);

  const openCommitDialog = useCallback(
    async (
      source: GitCommitDialogSource = "toolbar",
      request?: ManualGitCommitMessageRequest,
      draftKey?: string,
    ) => {
      diffNavigation.clearReturn();
      if (lifecycle.current && !request) {
        setCommitDialogOpen(true);
        return { state: commitDialogState, attemptId: lifecycle.current.id };
      }
      const draft = draftUI.read();
      const allowPrefill =
        !request &&
        !draft.edited &&
        !draft.message &&
        !draft.requiresRegeneration &&
        Boolean(
          autoGeneratedCommitMessageDraft &&
          !lifecycle.consumed(autoGeneratedCommitMessageDraft.key),
        );
      const attemptId = lifecycle.begin(
        source,
        draftKey ?? (allowPrefill ? autoGeneratedCommitMessageDraft?.key : undefined),
      );
      viewRevisionRef.current++;
      busyRef.current = false;
      openedManualRequestRef.current = request ?? null;
      reviewUI.clear();
      setCommitDialogOpen(true);
      setCommitDialogState(null);
      setCommitError(null);
      setGenerationPending(false);
      setMutationPending(false);
      setPublishPlan(null);
      setPublishRun(null);
      setPublishExpanded(false);
      setPublishOptions(createPublishOptions());
      setPublishCatalog({
        remotes: [],
        tags: [],
        unsupportedTags: [],
        loaded: false,
        loading: false,
        error: null,
      });
      readPresets();
      const state = await loadCommitDialogState({ allowPrefill, resetInclude: true, attemptId });
      return { state, attemptId };
    },
    [
      draftUI.read,
      commitDialogState,
      diffNavigation.clearReturn,
      autoGeneratedCommitMessageDraft,
      lifecycle,
      reviewUI.clear,
      readPresets,
      loadCommitDialogState,
    ],
  );

  useEffect(() => {
    const draftKey = autoGeneratedCommitMessageDraft?.key;
    if (executionPolicy.gitCommitReviewMode !== "draft-and-review" || !actionAvailable || !draftKey)
      return;
    if (lifecycle.current) {
      lifecycle.ignoreDraft(draftKey);
      return;
    }
    let scheduled = true;
    void Promise.resolve().then(() => {
      if (scheduled && lifecycle.canAutoOpen(draftKey))
        void openCommitDialog("automatic", undefined, draftKey);
    });
    return () => {
      scheduled = false;
    };
  }, [
    actionAvailable,
    autoGeneratedCommitMessageDraft?.key,
    executionPolicy.gitCommitReviewMode,
    commitDialogOpen,
    lifecycle,
    openCommitDialog,
  ]);

  const generateDialogMessage = useCallback(
    async (
      state: GitCommitDialogState,
      includeUnstaged: boolean,
      attemptId: number,
      preserveEdited = false,
    ) => {
      if (!isCurrent(attemptId) || busyRef.current) return;
      if (!getCommitDialogStagePaths(state, includeUnstaged, excludedFiles).length) {
        setCommitError(intl.formatMessage({ id: "git.actionMenu.commitDialog.error.noChanges" }));
        return;
      }
      const revision = viewRevisionRef.current;
      const ticket = reviewUI.begin();
      const current = () => isCurrent(attemptId, revision);
      const priorMessage = draftUI.read().message;
      busyRef.current = true;
      setGenerationPending(true);
      setCommitError(null);
      try {
        const selectionKey = JSON.stringify([
          includeUnstaged,
          excludedFiles,
          workspaceReview.read().data.selectedPaths,
        ]);
        const readSelectionKey = () =>
          JSON.stringify([
            workspaceReview.read().data.includeUnstaged,
            workspaceReview.read().data.excludedFiles,
            workspaceReview.read().data.selectedPaths,
          ]);
        const readGenerationVersions = () => {
          const fields = workspaceReview.read().snapshot.fieldRevisions;
          return JSON.stringify([
            fields.sourceReview,
            fields.includeUnstaged,
            fields.excludedFiles,
            fields.selectedPaths,
          ]);
        };
        await workspaceReview.flush();
        if (!current() || readSelectionKey() !== selectionKey) return;
        const generationVersions = readGenerationVersions();
        const conversationContext =
          openedManualRequestRef.current?.conversationContext ?? commitMessageConversationContext;
        const result = await gitService.generateCommitMessage({
          ...repositoryRequest,
          review: true,
          locale,
          includeUnstaged,
          ...(state.currentSessionFilePaths
            ? { currentSessionFilePaths: state.currentSessionFilePaths }
            : {}),
          ...(excludedFiles.length ? { excludedFilePaths: [...excludedFiles] } : {}),
          ...(conversationContext ? { conversationContext } : {}),
        });
        if (!current()) return;
        // 跨端审核与范围是 Host 事实；值恢复原样或另一端重建审核，也不能让旧模型结果覆盖新版本。
        if (readSelectionKey() !== selectionKey || readGenerationVersions() !== generationVersions)
          return;
        if (
          !reviewUI.adopt(
            result.review,
            ticket,
            result.reviewError ??
              (!result.review ? intl.formatMessage({ id: "git.review.unavailable" }) : undefined),
          )
        )
          return;
        const prior = draftUI.read();
        // 消息和审核引用同一次 admission，防止另一端看到新消息配旧审核的中间状态。
        workspaceReview.patch({
          browsePosition: 0,
          sourceReview: result.review ? { id: result.review.id } : null,
          selectedPaths: state.currentSessionFilePaths ?? null,
          draft: !result.message.trim()
            ? prior
            : preserveEdited || prior.message !== priorMessage
              ? { ...prior, requiresRegeneration: false }
              : {
                  message: result.message,
                  previousMessage: prior.message,
                  edited: false,
                  requiresRegeneration: false,
                },
        });
      } catch (error) {
        if (!current()) return;
        const failure = intl.formatMessage({
          id: "git.actionMenu.commitDialog.error.generateFailed",
        });
        logger.lifecycle.warn("[GitActionMenu] 生成提交消息失败", {
          workspacePath,
          error: getErrorMessage(error),
        });
        if (reviewUI.adopt(undefined, ticket, failure)) setCommitError(failure);
      } finally {
        if (current()) {
          busyRef.current = false;
          setGenerationPending(false);
        }
      }
    },
    [
      isCurrent,
      excludedFiles,
      intl,
      reviewUI.begin,
      reviewUI.adopt,
      draftUI.read,
      draftUI.generated,
      draftUI.regenerated,
      commitMessageConversationContext,
      gitService,
      repositoryRequest,
      locale,
      workspacePath,
    ],
  );

  useEffect(() => {
    const request = manualCommitMessageRequest;
    if (
      !request ||
      request.scopeKey !== scopeKey ||
      handledManualRequestKeyRef.current === request.key
    )
      return;
    let scheduled = true;
    void Promise.resolve().then(async () => {
      if (!scheduled) return;
      handledManualRequestKeyRef.current = request.key;
      if (
        (lifecycle.current && (busyRef.current || publishPlan || publishRun)) ||
        !actionAvailable ||
        !request.currentSessionFilePaths.length
      ) {
        if (lifecycle.current) setCommitDialogOpen(true);
        manualSettledCallbackRef.current?.(request.key);
        return;
      }
      pendingManualRequestKeyRef.current = request.key;
      try {
        const { state, attemptId } = await openCommitDialog("composer", request);
        if (state && isCurrent(attemptId))
          await generateDialogMessage(state, true, attemptId, draftUI.read().edited);
      } finally {
        settleManualRequest(request.key);
      }
    });
    return () => {
      scheduled = false;
    };
  }, [
    manualCommitMessageRequest,
    publishPlan,
    publishRun,
    scopeKey,
    lifecycle,
    actionAvailable,
    openCommitDialog,
    generateDialogMessage,
    isCurrent,
    draftUI.read,
    settleManualRequest,
  ]);

  const retryCommitDialogLoad = useCallback(async () => {
    const attemptId = lifecycle.current?.id;
    if (attemptId === undefined) return;
    const state = await loadCommitDialogState({ attemptId });
    // 手动生成入口的首次 refresh 失败后，重试仍需完成原生成请求；不要求再次关闭重开。
    if (state && openedManualRequestRef.current && isCurrent(attemptId)) {
      await generateDialogMessage(state, commitIncludeUnstaged, attemptId, draftUI.read().edited);
    }
  }, [
    lifecycle,
    loadCommitDialogState,
    isCurrent,
    generateDialogMessage,
    commitIncludeUnstaged,
    draftUI.read,
  ]);

  const refreshCommitDialogAfterBranchChange = useCallback(() => {
    invalidateReview();
    setPublishOptions(createPublishOptions());
    setPublishCatalog({
      remotes: [],
      tags: [],
      unsupportedTags: [],
      loaded: false,
      loading: false,
      error: null,
    });
    onRefreshGit();
    void loadCommitDialogState();
  }, [invalidateReview, onRefreshGit, loadCommitDialogState]);

  const currentCommitRequest = useCallback((): GitCommitRequest | null => {
    if (
      !commitDialogState ||
      draftUI.read().requiresRegeneration ||
      !reviewUI.canSubmit ||
      (reviewUI.review && browsePosition !== reviewUI.position)
    )
      return null;
    if (!hasGitCommitIdentity(commitDialogState.identity)) {
      setCommitError(intl.formatMessage({ id: "git.actionMenu.commitDialog.identityMissing" }));
      return null;
    }
    const paths = getCommitDialogStagePaths(
      commitDialogState,
      commitIncludeUnstaged,
      excludedFiles,
    );
    if (!paths.length) {
      setCommitError(intl.formatMessage({ id: "git.actionMenu.commitDialog.error.noChanges" }));
      return null;
    }
    const message = draftUI.read().message.trim();
    if (!message) return null;
    if (reviewUI.review && !reviewUI.group) return null;
    return {
      ...repositoryRequest,
      message,
      ...(reviewUI.review && reviewUI.group
        ? {
            review: {
              id: reviewUI.review.id,
              groupId: reviewUI.group.id,
              acknowledged: reviewUI.acknowledged,
            },
          }
        : { paths, stagedOnly: !commitIncludeUnstaged }),
    };
  }, [
    commitDialogState,
    draftUI.read,
    reviewUI.canSubmit,
    reviewUI.review,
    reviewUI.group,
    reviewUI.position,
    reviewUI.acknowledged,
    browsePosition,
    commitIncludeUnstaged,
    excludedFiles,
    repositoryRequest,
    intl,
  ]);

  const acceptCommit = useCallback(
    (result: GitCommitResult) => {
      const nextGroup = reviewUI.review?.groups[reviewUI.position + 1];
      if (reviewUI.review && reviewUI.group)
        reviewUI.advance(reviewUI.review.id, reviewUI.group.id);
      draftUI.committed(nextGroup?.message ?? "");
      workspaceReview.patch({ sourceReview: reviewUI.review ? { id: reviewUI.review.id } : null });
      if (nextGroup) {
        setBrowsePosition(reviewUI.position + 1);
      }
      setCommitDialogState((previous) =>
        previous ? { ...previous, summary: result.summary } : previous,
      );
      if (result.warning) {
        setCommitError(result.warning);
        reviewUI.adopt(undefined, undefined, result.warning);
        draftUI.invalidate();
      }
    },
    [
      reviewUI.review,
      reviewUI.group,
      reviewUI.position,
      reviewUI.advance,
      reviewUI.adopt,
      draftUI.committed,
      draftUI.invalidate,
    ],
  );

  const handleCommitSubmit = useCallback(async () => {
    const attemptId = lifecycle.current?.id;
    if (
      attemptId === undefined ||
      !isCurrent(attemptId) ||
      busyRef.current ||
      publishPlan ||
      publishRun ||
      !commitDialogState ||
      draftUI.read().requiresRegeneration ||
      !reviewUI.canSubmit
    )
      return;
    if (!draftUI.read().message.trim()) {
      await generateDialogMessage(commitDialogState, commitIncludeUnstaged, attemptId);
      return;
    }
    const request = currentCommitRequest();
    if (!request) return;
    const revision = viewRevisionRef.current;
    const current = () => isCurrent(attemptId, revision);
    busyRef.current = true;
    setMutationPending(true);
    setCommitError(null);
    try {
      // commit(paths, stagedOnly) 已负责选定路径；提前 stage 会使冻结 index 失效且多出副作用入口。
      const result = await gitService.commit(request);
      if (!current()) return;
      acceptCommit(result);
      onRefreshGit();
      if (result.warning) return;
      toast(intl.formatMessage({ id: "git.actionMenu.commitDialog.toast.success" }));
      if (!reviewUI.review?.groups[reviewUI.position + 1]) {
        // 最终成功清空草稿，不能由关闭分支重新标为旧审核草稿。
        lifecycle.close();
        reviewUI.clear();
        setCommitDialogOpen(false);
        setCommitDialogState(null);
        setPublishPlan(null);
        setPublishRun(null);
        busyRef.current = false;
        setMutationPending(false);
        settleManualRequest();
      }
    } catch (error) {
      if (current())
        setCommitError(
          intl.formatMessage(
            { id: "git.actionMenu.commitDialog.error.requestFailed" },
            {
              error: getCheckoutOperationErrorMessage(
                error,
                intl.formatMessage({ id: "git.commitWorkflow.directoryBusy" }),
              ),
            },
          ),
        );
    } finally {
      if (current()) {
        busyRef.current = false;
        setMutationPending(false);
      }
    }
  }, [
    lifecycle,
    isCurrent,
    publishPlan,
    publishRun,
    commitDialogState,
    draftUI.read,
    reviewUI.canSubmit,
    reviewUI.review,
    reviewUI.position,
    reviewUI.clear,
    generateDialogMessage,
    commitIncludeUnstaged,
    currentCommitRequest,
    gitService,
    acceptCommit,
    onRefreshGit,
    intl,
    settleManualRequest,
  ]);

  const loadPublishCatalog = useCallback(async () => {
    const attemptId = lifecycle.current?.id;
    if (attemptId === undefined || !isCurrent(attemptId)) return;
    const revision = viewRevisionRef.current;
    const ticket = ++catalogTicketRef.current;
    const current = () => isCurrent(attemptId, revision) && ticket === catalogTicketRef.current;
    setPublishCatalog((prior) => ({ ...prior, loading: true, error: null }));
    try {
      const [remoteResult, tagResult] = await Promise.all([
        gitService.listRemotes(repositoryRequest),
        gitService.listTags(repositoryRequest),
      ]);
      if (current())
        setPublishCatalog({
          remotes: remoteResult.remotes,
          tags: tagResult.tags,
          unsupportedTags: tagResult.unsupportedTags ?? [],
          loaded: true,
          loading: false,
          error: null,
        });
    } catch (error) {
      if (current())
        setPublishCatalog((prior) => ({
          ...prior,
          loading: false,
          loaded: false,
          error: getErrorMessage(error),
        }));
    }
  }, [lifecycle, isCurrent, gitService, repositoryRequest]);

  const previewPublication = useCallback(
    async (withCommit: boolean) => {
      const attemptId = lifecycle.current?.id;
      if (
        attemptId === undefined ||
        !isCurrent(attemptId) ||
        busyRef.current ||
        publishPlan ||
        publishRun ||
        !commitDialogState
      )
        return;
      if (withCommit && reviewUI.review && reviewUI.position < reviewUI.review.groups.length - 1)
        return;
      const commit = withCommit ? currentCommitRequest() : null;
      if (withCommit && !commit) return;
      const revision = viewRevisionRef.current;
      const current = () => isCurrent(attemptId, revision);
      busyRef.current = true;
      setMutationPending(true);
      setCommitError(null);
      try {
        const [state, remoteResult, tagResult] = await Promise.all([
          gitService.getPublishState(repositoryRequest),
          gitService.listRemotes(repositoryRequest),
          gitService.listTags(repositoryRequest),
        ]);
        if (!current()) return;
        const validation = validatePublishOptions(publishOptions, {
          state,
          remotes: remoteResult.remotes,
          tags: tagResult.tags,
          unsupportedTags: tagResult.unsupportedTags,
          withCommit,
        });
        if (validation) {
          setCommitError(intl.formatMessage({ id: `git.publish.error.${validation}` }));
          return;
        }
        setPublishCatalog({
          remotes: remoteResult.remotes,
          tags: tagResult.tags,
          unsupportedTags: tagResult.unsupportedTags ?? [],
          loaded: true,
          loading: false,
          error: null,
        });
        const files = withCommit
          ? (reviewUI.group?.files.map((file) => file.path) ??
            getCommitDialogFiles(commitDialogState, commitIncludeUnstaged, excludedFiles).map(
              (file) => file.repoRelativePath,
            ))
          : [];
        setPublishPlan(
          freezePublishPlan({
            request: repositoryRequest,
            options: publishOptions,
            state,
            tags: tagResult.tags,
            files: [...new Set(files)],
            commit,
          }),
        );
      } catch (error) {
        if (current()) setCommitError(getErrorMessage(error));
      } finally {
        if (current()) {
          busyRef.current = false;
          setMutationPending(false);
        }
      }
    },
    [
      lifecycle,
      isCurrent,
      publishPlan,
      publishRun,
      commitDialogState,
      reviewUI.review,
      reviewUI.position,
      reviewUI.group,
      currentCommitRequest,
      gitService,
      repositoryRequest,
      publishOptions,
      intl,
      commitIncludeUnstaged,
      excludedFiles,
    ],
  );

  const confirmPublication = useCallback(async () => {
    const attemptId = lifecycle.current?.id;
    if (
      attemptId === undefined ||
      !isCurrent(attemptId) ||
      busyRef.current ||
      !publishPlan ||
      publishRun
    )
      return;
    const revision = viewRevisionRef.current;
    const current = () => isCurrent(attemptId, revision);
    busyRef.current = true;
    setMutationPending(true);
    setCommitError(null);
    try {
      await executePublishPlan({
        service: gitService,
        plan: publishPlan,
        isCurrent: current,
        onUpdate: setPublishRun,
        onCommitted: acceptCommit,
      });
      if (current()) onRefreshGit();
    } finally {
      if (current()) {
        busyRef.current = false;
        setMutationPending(false);
      }
    }
  }, [lifecycle, isCurrent, publishPlan, publishRun, gitService, acceptCommit, onRefreshGit]);

  const retryPublication = useCallback(
    async (stepId: string) => {
      const attemptId = lifecycle.current?.id;
      if (attemptId === undefined || !isCurrent(attemptId) || busyRef.current || !publishRun)
        return;
      const revision = viewRevisionRef.current;
      const current = () => isCurrent(attemptId, revision);
      busyRef.current = true;
      setMutationPending(true);
      try {
        await retryPublishStep({
          service: gitService,
          run: publishRun,
          stepId,
          isCurrent: current,
          onUpdate: setPublishRun,
        });
        if (current()) onRefreshGit();
      } finally {
        if (current()) {
          busyRef.current = false;
          setMutationPending(false);
        }
      }
    },
    [lifecycle, isCurrent, publishRun, gitService, onRefreshGit],
  );

  const persistPresets = useCallback(
    (next: PublishPreset[]) => {
      try {
        localStorage.setItem(presetKey, serializePublishPresets(next));
        setPresets(next);
        return true;
      } catch (error) {
        setCommitError(
          intl.formatMessage(
            { id: "git.publish.error.presets" },
            { error: getErrorMessage(error) },
          ),
        );
        return false;
      }
    },
    [presetKey, intl],
  );

  const copyMessage = useCallback(async () => {
    const attemptId = lifecycle.current?.id;
    if (attemptId === undefined) return;
    try {
      if (!platform?.writeClipboardText)
        throw new Error(intl.formatMessage({ id: "git.message.clipboardUnavailable" }));
      await platform.writeClipboardText(draftUI.read().message);
      if (isCurrent(attemptId)) toast(intl.formatMessage({ id: "git.message.copied" }));
    } catch (error) {
      if (isCurrent(attemptId))
        setCommitError(
          intl.formatMessage({ id: "git.message.copyFailed" }, { error: getErrorMessage(error) }),
        );
    }
  }, [lifecycle, platform, intl, draftUI.read, isCurrent]);

  const handlePrimaryAction = useCallback(() => {
    if (primaryActionDisabled) return;
    runUserAction({
      input: { featureId: "workbench.git", action: "open", trigger: "button" },
      operation: () => {
        void openCommitDialog();
      },
      completed: { resultSource: "local_commit" },
      failureStage: "git_action_open",
    });
  }, [primaryActionDisabled, openCommitDialog]);

  const renderDialog = (prepare?: ReactNode, merge?: ReactNode, operationId?: string) => (
    <GitCommitDialog
      open={commitDialogOpen && Boolean(lifecycle.current)}
      executionMode={executionMode}
      worktreeActions={prepare}
      worktreeMergeActions={merge}
      mergeOperationId={operationId}
      mergeView={workspaceReview.data.mergeView}
      onMergeViewChange={(value) => workspaceReview.patch({ mergeView: value })}
      syncBlocked={workspaceReview.status !== "ready"}
      syncStatus={
        <ReviewWorkspaceSyncStatus
          status={workspaceReview.status}
          onRetry={() => void workspaceReview.retry()}
          onResolve={workspaceReview.resolve}
        />
      }
      loading={commitDialogLoading}
      state={commitDialogState}
      workspacePath={workspacePath}
      onOpenFiles={() => openReviewFiles()}
      onOpenScopeFiles={() => openReviewFiles(true)}
      canOpenFiles={diffNavigation.available}
      message={draftUI.draft.message}
      previousMessage={draftUI.draft.previousMessage}
      error={commitError}
      mutationPending={mutationPending}
      generationPending={generationPending}
      includeUnstaged={commitIncludeUnstaged}
      requiresRegeneration={draftUI.draft.requiresRegeneration}
      reviewError={reviewUI.error}
      review={reviewUI.review}
      reviewPosition={reviewUI.position}
      browsePosition={browsePosition}
      excludedFiles={excludedFiles}
      reviewAcknowledged={reviewUI.acknowledged}
      reviewCanSubmit={reviewUI.canSubmit}
      onVisible={reportCommitDialogVisible}
      onOpenChange={(open) => {
        if (!open) closeCommitDialog();
      }}
      onRetryLoad={() => {
        void retryCommitDialogLoad();
      }}
      onMessageChange={(value) => {
        reviewUI.acknowledge(false);
        draftUI.edit(value);
      }}
      onCopyMessage={() => {
        void copyMessage();
      }}
      onRestoreMessage={draftUI.restore}
      onReviewAcknowledge={reviewUI.acknowledge}
      onBrowse={setBrowsePosition}
      onManualFallback={() => {
        if (!draftUI.draft.requiresRegeneration) {
          reviewUI.clear();
          workspaceReview.patch({ sourceReview: null });
        }
      }}
      onIncludeUnstagedChange={(value) => {
        invalidateReview();
        setCommitIncludeUnstaged(value);
      }}
      onRefreshGit={refreshCommitDialogAfterBranchChange}
      onGenerateMessage={() => {
        const attemptId = lifecycle.current?.id;
        if (commitDialogState && attemptId !== undefined)
          void generateDialogMessage(commitDialogState, commitIncludeUnstaged, attemptId);
      }}
      onSubmit={() => {
        void handleCommitSubmit();
      }}
      plan={publishPlan}
      run={publishRun}
      onConfirmPublish={() => {
        void confirmPublication();
      }}
      onCancelPreview={() => setPublishPlan(null)}
      onRetryPublish={(id) => {
        void retryPublication(id);
      }}
      onResetPublish={() => {
        setPublishPlan(null);
        setPublishRun(null);
        // 重新规划不能把未完成/已失效的审核静默降级成普通手动提交。
        if (reviewUI.review || reviewUI.error) invalidateReview();
        else reviewUI.clear();
        void loadCommitDialogState();
        void loadPublishCatalog();
      }}
      publish={{
        expanded: publishExpanded,
        options: publishOptions,
        remotes: publishCatalog.remotes,
        tags: publishCatalog.tags,
        unsupportedTags: publishCatalog.unsupportedTags,
        loading: publishCatalog.loading,
        error: publishCatalog.error,
        presets,
        presetName,
        selectedPreset,
        onToggle: () => {
          setPublishExpanded(!publishExpanded);
          if (!publishExpanded && !publishCatalog.loaded && !publishCatalog.loading)
            void loadPublishCatalog();
        },
        onReload: () => {
          void loadPublishCatalog();
        },
        onChange: setPublishOptions,
        onPreview: (withCommit) => {
          void previewPublication(withCommit);
        },
        onPresetNameChange: setPresetName,
        onPresetSelect: setSelectedPreset,
        onPresetSave: () => {
          const name = presetName.trim();
          if (
            name &&
            persistPresets([
              ...presets.filter((preset) => preset.name !== name),
              { name, options: publishOptions },
            ])
          )
            setSelectedPreset(name);
        },
        onPresetApply: () => {
          const preset = presets.find((item) => item.name === selectedPreset);
          if (preset)
            setPublishOptions(
              applyPublishPreset(
                preset,
                publishCatalog.tags.map((tag) => tag.name),
              ),
            );
        },
        onPresetDelete: () => {
          if (persistPresets(presets.filter((preset) => preset.name !== selectedPreset)))
            setSelectedPreset("");
        },
      }}
    />
  );

  return (
    <>
      <div
        onClick={isStatusRowTrigger && !triggerIconOnly ? handlePrimaryAction : undefined}
        className={cn(
          "flex h-7 items-center overflow-hidden rounded-lg border border-border bg-input transition-colors hover:border-border-hover @max-[560px]/workspace-header:w-7 @max-[560px]/workspace-header:justify-center",
          triggerIconOnly && "w-7 justify-center",
          isStatusRowTrigger &&
            "h-8 w-full justify-start rounded-lg border-0 bg-transparent hover:border-transparent hover:bg-hover @max-[560px]/workspace-header:w-full @max-[560px]/workspace-header:justify-start",
          className,
        )}
      >
        <Button
          data-testid="git-action-trigger"
          type="button"
          variant="ghost"
          size="default"
          disabled={primaryActionDisabled}
          aria-label={workflowTitle}
          className={cn(
            "h-7 gap-1 rounded-lg border-0 px-1.5 @max-[560px]/workspace-header:w-7 @max-[560px]/workspace-header:px-0 @max-[560px]/workspace-header:[&>span]:hidden",
            triggerIconOnly && "w-7 px-0 [&>span]:hidden",
            isStatusRowTrigger &&
              "h-8 min-w-0 w-full justify-start gap-2 px-2 text-left text-ui-base hover:bg-transparent @max-[560px]/workspace-header:w-auto @max-[560px]/workspace-header:[&>span]:inline",
          )}
          onClick={isStatusRowTrigger && !triggerIconOnly ? undefined : handlePrimaryAction}
        >
          {triggerPending ? (
            <LoaderIcon className="size-4 animate-spin text-foreground-subtle" />
          ) : primaryActionId === "push" ? (
            <ArrowUpFromLine className="size-4" />
          ) : (
            <GitCommitIcon className="size-4" />
          )}
          <span className={cn(isStatusRowTrigger && "min-w-0 truncate")}>{workflowTitle}</span>
        </Button>
      </div>
      {executionBindingId && executionSessionId ? (
        <CommitAndMergeControl
          workspacePath={workspacePath}
          workspaceIdentity={workspaceIdentity}
          workspaceRemoteSessionId={workspaceRemoteSessionId}
          originWorkspacePath={originWorkspacePath ?? workspacePath}
          originWorkspaceIdentity={originWorkspaceIdentity ?? workspaceIdentity}
          sessionId={executionSessionId}
          reviewRevision={String(workspaceReview.snapshot.fieldRevisions.integrationId)}
          review={reviewUI.review}
          position={reviewUI.position}
          currentMessage={draftUI.draft.message}
          disabled={
            workspaceReview.status !== "ready" ||
            triggerPending ||
            Boolean(publishPlan || publishRun) ||
            draftUI.draft.requiresRegeneration
          }
          onHideReview={() => setCommitDialogOpen(false)}
          onShowReview={() => setCommitDialogOpen(true)}
          onCommitted={(operation) => {
            workspaceReview.patch({
              integrationId: operation.id,
              mergeView: null,
              sourceReview: reviewUI.review ? { id: reviewUI.review.id } : null,
            });
            let nextPosition = reviewUI.position;
            for (const receipt of operation.sourceReceipts ?? []) {
              nextPosition = advanceCommitReviewPosition(reviewUI.review, nextPosition, {
                id: receipt.reviewId,
                groupId: receipt.groupId,
              });
              reviewUI.advance(receipt.reviewId, receipt.groupId);
            }
            // 重试返回全部持久收据，只有与当前组匹配的收据才能推进草稿位置。
            const remainingGroup = reviewUI.review?.groups[nextPosition];
            draftUI.committed(remainingGroup?.message ?? "");
            onRefreshGit();
            void loadCommitDialogState();
          }}
          renderDialog={(prepare, merge, operationId) => renderDialog(prepare, merge, operationId)}
        />
      ) : (
        renderDialog()
      )}
    </>
  );
}
