export const MEMORY_RECALL_FILE_LIMIT = 200;
export const MEMORY_RECALL_SCAN_CONCURRENCY = 8;
export const MEMORY_RECALL_DIRECTORY_LIMIT = 128;
export const MEMORY_RECALL_DIRECTORY_ENTRY_LIMIT = 4_096;
export const MEMORY_RECALL_INDEX_FILE_MAX_BYTES = 64 * 1024;
export const MEMORY_RECALL_CORPUS_MAX_BYTES = 4 * 1024 * 1024;
export const MEMORY_RECALL_RESULT_LIMIT = 4;
export const MEMORY_RECALL_RESULT_CHARACTER_LIMIT = 4_000;
export const MEMORY_RECALL_ATTACHMENT_CHARACTER_LIMIT = 12_000;

export const MEMORY_RECALL_BM25_K1 = 1.2;
export const MEMORY_RECALL_BM25_B = 0.75;
export const MEMORY_RECALL_METADATA_MATCH_BOOST = 0.25;
export const MEMORY_RECALL_METADATA_BOOST_LIMIT = 1;
