/// <reference types="vite/client" />
import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import type { IServiceAccessor, IGitService } from "@lcode/services";
import type { GitFileChange, GitRepositorySummary } from "@lcode/shared";
import type { ConversationRow } from "@lcode/shared/lcode-protocol-v4";
import { GitActionMenu } from "@/GitActionMenu.js";
import { ServiceProvider } from "@/hooks/useServices.js";
import { PlatformProvider } from "@/hooks/usePlatform.js";
import { LCodeIntlProvider } from "@/i18n/IntlProvider.js";
import { useSessionCommitMessageFiles } from "@/hooks/useSessionCommitMessageFiles.js";
import {
  V4ConversationContext,
  type V4ConversationContextValue,
} from "@/v4/V4ConversationContext.js";
import { ConversationCommitMessageButton } from "@/v4/composer/ConversationCommitMessageButton.js";
import {
  canGenerateSessionCommitSummary,
  type ManualGitCommitMessageRequest,
  type AutoGeneratedGitCommitMessageDraft,
} from "@/git-action-menu/autoCommitMessage.js";
import { buildGitChangesFingerprint } from "@/git-action-menu/currentSessionFileScope.js";
import { TooltipProvider } from "@/components/ui/tooltip.js";
import { platform } from "./git-backup-platform.js";
import "@lcode/ui/styles.css";

const workspacePath = "/fixture/repo";
const workspaceIdentity = "fixture-host/repo";
let dirtyPaths = ["a.ts", "b.ts", "workflow.ts"];
let failLoad = false;
let holdGenerate = false;
let failGenerate = false;
let releaseGeneration: (() => void) | null = null;
let requestSequence = 0;
const calls: Parameters<IGitService["generateCommitMessage"]>[0][] = [];
const rowsQueries: string[] = [];
function summary(): GitRepositorySummary {
  return {
    workspacePath,
    repoRoot: workspacePath,
    workspaceInRepoPath: ".",
    autoRefreshWatchPaths: [],
    branchName: "fixture",
    trackingBranchName: null,
    headRefType: "branch",
    ahead: 0,
    behind: 0,
    isDirty: dirtyPaths.length > 0,
    isGitAvailable: true,
    isRepository: true,
  };
}
function file(path: string): GitFileChange {
  return {
    path,
    repoRelativePath: path,
    workspaceRelativePath: path,
    kind: "modified",
    section: "unstaged",
    added: 1,
    removed: 0,
    isStaged: false,
    isUntracked: false,
    isConflicted: false,
  };
}
const gitService = {
  async refresh(params) {
    if (params.includeIdentity && failLoad) {
      failLoad = false;
      throw new Error("fixture-load-failure");
    }
    return {
      summary: summary(),
      stagedChanges: [],
      unstagedChanges: dirtyPaths.map(file),
      identity: {
        userName: "Fixture",
        userEmail: "fixture@example.invalid",
        nameSource: "fixture",
        emailSource: "fixture",
      },
    };
  },
  async generateCommitMessage(params) {
    calls.push(params);
    if (failGenerate) {
      failGenerate = false;
      throw new Error("fixture-generation-failure");
    }
    if (holdGenerate) {
      holdGenerate = false;
      await new Promise<void>((resolve) => {
        releaseGeneration = resolve;
      });
    }
    const message = `修复 ${params.conversationContext?.sessionId ?? "fixture"} 的布局适配`;
    return {
      message,
      providerId: "fixture",
      model: "fixture",
      review: {
        id: `review-${calls.length}`,
        mode: "merged",
        warnings: [],
        groups: [
          {
            id: "group",
            label: "当前会话变更",
            sessionIds: [params.conversationContext?.sessionId ?? "fixture"],
            message,
            dependsOn: [],
            requiresConfirmation: true,
            files: (params.currentSessionFilePaths ?? []).map((path) => ({
              path,
              added: 1,
              removed: 0,
              patch: `diff --git a/${path} b/${path}\n+fixture change`,
            })),
          },
        ],
      },
    };
  },
} as IGitService;
const services = {
  gitService,
  lcodeAgentService: {
    async listSessionSubagents({ sessionId }: { sessionId: string }) {
      return {
        revision: 1,
        childSessionIds: sessionId === "workflow" ? ["actor"] : [],
        running: [],
        ended: { total: 0, items: [] },
      };
    },
  },
} as unknown as IServiceAccessor;
const conversation = {
  async rowsRange({ sessionId }: { sessionId: string }) {
    rowsQueries.push(sessionId);
    const hasChanges = ["a", "b", "actor"].includes(sessionId);
    const rows: ConversationRow[] = hasChanges
      ? [
          {
            kind: "turnHeader",
            rowId: 1,
            entityId: "turn",
            turnId: "turn",
            origin: "userInput",
            state: "completedSuccess",
            startedAt: 1,
            createdAt: 1,
            createdAtSeq: 1,
            fileChanges: { files: 1, additions: 1, deletions: 0, state: "active" },
          } as ConversationRow,
        ]
      : [];
    return { rows, hasMore: false, atRevision: 1, atSeq: 1, atLogEpoch: sessionId };
  },
  async fileChanges({ sessionId }: { sessionId: string }) {
    return {
      files: 1,
      additions: 1,
      deletions: 0,
      state: "active",
      items: [
        {
          path: sessionId === "actor" ? "workflow.ts" : `${sessionId}.ts`,
          additions: 1,
          deletions: 0,
          writeCount: 1,
          toolNames: ["Edit"],
          patches: [],
        },
      ],
    };
  },
} as unknown as V4ConversationContextValue;

function FixtureApp() {
  const [sessionId, setSessionId] = useState("a");
  const [enabled, setEnabled] = useState(true);
  const [revision, setRevision] = useState(0);
  const [request, setRequest] = useState<ManualGitCommitMessageRequest | null>(null);
  const [pending, setPending] = useState<string | null>(null);
  const [hidden, setHidden] = useState(false);
  const [automaticDraft, setAutomaticDraft] = useState<AutoGeneratedGitCommitMessageDraft | null>(
    null,
  );
  const scopeKey = JSON.stringify([workspaceIdentity, "remote-fixture", sessionId]);
  const eligible = canGenerateSessionCommitSummary({
    enabled,
    sessionId,
    readOnly: false,
    sideChat: false,
    phase: "completedSuccess",
    repositoryAvailable: true,
    repositoryDirty: dirtyPaths.length > 0,
  });
  const paths = useSessionCommitMessageFiles({
    enabled: eligible,
    scopeKey,
    sessionId,
    workspacePath,
    workspaceIdentity,
    remoteSessionId: "fixture-remote",
    candidatePathsKey: "[]",
    childSessionIdsKey: "[]",
    refreshKey: `${revision}`,
  });
  (globalThis as typeof globalThis & { __gitCommitFixture: unknown }).__gitCommitFixture = {
    calls,
    rowsQueries,
    switchSession: (id: string) => {
      setSessionId(id);
      setRequest(null);
      setPending(null);
    },
    setting: (value: boolean) => setEnabled(value),
    dirty: (paths: string[]) => {
      dirtyPaths = paths;
      setRevision((value) => value + 1);
    },
    failLoad: () => {
      failLoad = true;
    },
    failGenerate: () => {
      failGenerate = true;
    },
    holdGeneration: () => {
      holdGenerate = true;
    },
    release: () => {
      releaseGeneration?.();
      releaseGeneration = null;
    },
    hideMenu: () => setHidden(true),
    rerender: () => setRevision((value) => value + 1),
    automatic: () => {
      const message = "自动生成的中文提交纪要";
      setAutomaticDraft({
        key: `automatic-${++requestSequence}`,
        message,
        currentSessionFilePaths: ["a.ts"],
        gitFingerprint: buildGitChangesFingerprint({
          files: dirtyPaths.map(file),
          currentSessionFilePaths: ["a.ts"],
          gitSummary: summary(),
          workspacePath,
        })!,
        review: {
          id: "automatic-review",
          mode: "merged",
          warnings: [],
          groups: [
            {
              id: "automatic-group",
              label: "当前会话",
              sessionIds: [sessionId],
              dependsOn: [],
              message,
              requiresConfirmation: true,
              files: [{ path: "a.ts", patch: "+fixture", added: 1, removed: 0 }],
            },
          ],
        },
      });
    },
  };
  return (
    <div className="p-4 text-foreground">
      <p data-testid="session">{sessionId}</p>
      <textarea data-testid="composer-draft" defaultValue="待发送的草稿不能改变" />
      <div className="flex items-center justify-end gap-1">
        <button type="button">发送</button>
        <ConversationCommitMessageButton
          pending={pending !== null}
          onClick={
            eligible && paths.length > 0
              ? () => {
                  const key = `${scopeKey}/${++requestSequence}`;
                  setPending(key);
                  setRequest({
                    key,
                    scopeKey,
                    currentSessionFilePaths: paths,
                    conversationContext: {
                      sessionId,
                      messages: [{ role: "user", text: `修复 ${sessionId} 的布局` }],
                    },
                  });
                }
              : undefined
          }
        />
      </div>
      <div className={hidden ? "hidden" : ""}>
        <GitActionMenu
          key={scopeKey}
          workspacePath={workspacePath}
          workspaceIdentity={workspaceIdentity}
          dialogScopeKey={scopeKey}
          gitSummary={summary()}
          manualCommitMessageRequest={request}
          autoGeneratedCommitMessageDraft={automaticDraft}
          onManualCommitMessageSettled={(key) => {
            setPending((prior) => (prior === key ? null : prior));
            setRequest((prior) => (prior?.key === key ? null : prior));
          }}
          onRefreshGit={() => setRevision((value) => value + 1)}
        />
      </div>
    </div>
  );
}
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <ServiceProvider services={services}>
      <PlatformProvider platform={platform}>
        <LCodeIntlProvider initialLocale="zh-CN">
          <TooltipProvider>
            <V4ConversationContext.Provider value={conversation}>
              <FixtureApp />
            </V4ConversationContext.Provider>
          </TooltipProvider>
        </LCodeIntlProvider>
      </PlatformProvider>
    </ServiceProvider>
  </StrictMode>,
);
