import { useState } from "react";
import { createRoot } from "react-dom/client";
import type { GitCommitReview, GitRepositorySummary, GitFileChange } from "@lcode/shared";
import type { IServiceAccessor, IGitService } from "@lcode/services";
import { ServiceProvider } from "@/hooks/useServices.js";
import { PlatformProvider } from "@/hooks/usePlatform.js";
import { LCodeIntlProvider } from "@/i18n/IntlProvider.js";
import { GitActionMenu } from "@/GitActionMenu.js";
import { TooltipProvider } from "@/components/ui/tooltip.js";
import { buildGitChangesFingerprint } from "@/git-action-menu/currentSessionFileScope.js";
import { platform } from "./git-backup-platform.js";
import "@lcode/ui/styles.css";

const workspacePath = "/fixture";
const summary: GitRepositorySummary = {
  workspacePath,
  repoRoot: workspacePath,
  workspaceInRepoPath: "",
  autoRefreshWatchPaths: [],
  branchName: "test",
  headRefType: "branch",
  trackingBranchName: null,
  ahead: 0,
  behind: 0,
  isDirty: true,
  isGitAvailable: true,
  isRepository: true,
};
const change: GitFileChange = {
  path: "/fixture/x.ts",
  repoRelativePath: "x.ts",
  workspaceRelativePath: "x.ts",
  kind: "modified",
  section: "unstaged",
  added: 2,
  removed: 2,
  isStaged: false,
  isUntracked: false,
  isConflicted: false,
};
const review: GitCommitReview = {
  id: "fixture-review",
  mode: "ordered",
  warnings: [],
  groups: [
    {
      id: "A",
      label: "会话 A：新增功能",
      sessionIds: ["A"],
      dependsOn: [],
      message: "feat: 新增功能",
      requiresConfirmation: true,
      files: [{ path: "x.ts", patch: "@@ -1 +1 @@\n-old\n+feature A", added: 1, removed: 1 }],
    },
    {
      id: "B",
      label: "会话 B：增强功能",
      sessionIds: ["B"],
      dependsOn: ["A"],
      message: "feat: 增强功能",
      requiresConfirmation: true,
      files: [{ path: "x.ts", patch: "@@ -1 +1 @@\n-feature A\n+feature B", added: 1, removed: 1 }],
    },
  ],
};
function Fixture() {
  const mode = new URLSearchParams(window.location.search);
  const [commits, setCommits] = useState<string[]>([]);
  const [stages, setStages] = useState(0);
  const [stale, setStale] = useState(mode.has("stale"));
  const service = {
    refresh: async () => ({
      summary,
      identity: {
        userName: "Fixture",
        userEmail: "fixture@example.invalid",
        nameSource: "local",
        emailSource: "local",
      },
      unstagedChanges: [change],
      stagedChanges: [],
      branchComparison: null,
    }),
    generateCommitMessage: async () => ({
      message: review.groups[0]!.message,
      review,
      providerId: "fixture",
      model: "fixture",
    }),
    stagePaths: async () => {
      setStages((value) => value + 1);
    },
    commit: async (params) => {
      if (stale) throw new Error("Git 内容已变化，请重新审核后提交。");
      setCommits((prior) => [...prior, params.review?.groupId ?? "manual"]);
      return { commitHash: "fixture", summary };
    },
  } as IGitService;
  const draft = {
    key: "fixture-completed-turn",
    message: review.groups[0]!.message,
    ...(mode.has("error")
      ? { reviewError: "二进制不能按行拆分，请明确选择普通手动提交。" }
      : { review }),
    currentSessionFilePaths: [change.path],
    gitFingerprint: buildGitChangesFingerprint({
      files: [change],
      currentSessionFilePaths: [change.path],
      gitSummary: summary,
      workspacePath,
    }),
  };
  return (
    <TooltipProvider>
      <PlatformProvider platform={platform}>
        <ServiceProvider services={{ gitService: service } as IServiceAccessor}>
          <LCodeIntlProvider initialLocale="zh-CN">
            <main className="p-4 text-ui-base">
              <h1>自动完成弹窗回归夹具</h1>
              <output data-testid="fixture-commits">{commits.join(",") || "none"}</output>
              <output data-testid="fixture-stages">{stages}</output>
              <button type="button" onClick={() => setStale(true)}>
                模拟外部写入
              </button>
              <GitActionMenu
                workspacePath={workspacePath}
                gitSummary={summary}
                autoGeneratedCommitMessageDraft={draft}
                onRefreshGit={() => {}}
              />
            </main>
          </LCodeIntlProvider>
        </ServiceProvider>
      </PlatformProvider>
    </TooltipProvider>
  );
}
createRoot(document.getElementById("root")!).render(<Fixture />);
