/// <reference types="vite/client" />
import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import type {
  IServiceAccessor,
  IGitService,
  WorktreeBinding,
  WorktreeIntegration,
  WorktreeIntegrateRequest,
} from "@lcode/services";
import type {
  AppSettings,
  GitCommitReviewMode,
  GitFileChange,
  GitRepositorySummary,
} from "@lcode/shared";
import { gitCommitReviewModeSchema, replaceRemoteWorkspaceIdentityPath } from "@lcode/shared";
import type { ConversationRow } from "@lcode/shared/lcode-protocol-v4";
import { useGitFailureDraftReceiver } from "@/hooks/useGitFailureHandoff.js";
import { appendGitFailureDraft } from "@/git-action-menu/gitFailureDraft.js";
import { GitActionMenu } from "@/GitActionMenu.js";
import { ServiceProvider } from "@/hooks/useServices.js";
import { useSettings } from "@/hooks/useSettingService.js";
import { useProjectExecutionPolicy } from "@/hooks/useProjectExecutionPolicy.js";
import { PlatformProvider } from "@/hooks/usePlatform.js";
import { TabStoreProvider } from "@/store/TabStoreProvider.js";
import { useRemoteWorkspaceSessionStore } from "@/store/remoteWorkspaceSessionStore.js";
import { LCodeIntlProvider } from "@/i18n/IntlProvider.js";
import { useSessionCommitMessageFiles } from "@/hooks/useSessionCommitMessageFiles.js";
import {
  V4ConversationContext,
  type V4ConversationContextValue,
} from "@/v4/V4ConversationContext.js";
import { ConversationCommitMessageButton } from "@/v4/composer/ConversationCommitMessageButton.js";
import { ConversationStatusPanel } from "@/v4/ConversationStatusPanel.js";
import {
  canGenerateSessionCommitSummary,
  buildGitCommitMessageScopeKey,
  type ManualGitCommitMessageRequest,
  type AutoGeneratedGitCommitMessageDraft,
} from "@/git-action-menu/autoCommitMessage.js";
import { buildGitChangesFingerprint } from "@/git-action-menu/currentSessionFileScope.js";
import { TooltipProvider } from "@/components/ui/tooltip.js";
import { platform } from "./git-backup-platform.js";
import { createPublishFixture } from "./git-publish-fixture-service.js";
import { FixtureReviewPreview } from "./review-preview.js";
import { createReviewWorkspaceFixture } from "./review-workspace-service.js";
import type { GitCommitReview } from "@lcode/shared";
import "@lcode/ui/styles.css";

const workspacePath = "/fixture/repo";
const useProductionSidePane = new URLSearchParams(window.location.search).has("shellPreview");
const showStatusPanel = new URLSearchParams(window.location.search).has("panel");
const workspaceIdentity = new URLSearchParams(window.location.search).has("pathOnly")
  ? undefined
  : (new URLSearchParams(window.location.search).get("identity") ?? "fixture-host/repo");
const previewRemoteSessionId =
  useProductionSidePane && workspaceIdentity ? "fixture-preview-attachment" : undefined;
let dirtyPaths = ["a.ts", "b.ts", "workflow.ts"];
let loadFailure: Error | null = null;
let holdGenerate = false;
let failGenerate = false;
let reviewUnavailable = false;
let releaseGeneration: (() => void) | null = null;
let requestSequence = 0;
let groupedReview = false;
let hasTracking = false;
const calls: Parameters<IGitService["generateCommitMessage"]>[0][] = [];
let fixtureIntegration: WorktreeIntegration | null = null;
const seedStatus = new URLSearchParams(location.search).get("seedIntegration");
if (
  ["cancelled", "failed", "source-commit-failed", "published", "ready"].includes(seedStatus ?? "")
) {
  fixtureIntegration = {
    id: "historical-operation",
    requestId: "historical-request",
    bindingId: "fixture-binding",
    sourceHead: "s".repeat(40),
    targetHead: "t".repeat(40),
    candidateHead: "c".repeat(40),
    targetBranch: "L-GO",
    targetPath: workspacePath,
    checkoutPath: "/fixture/integration",
    status: seedStatus as WorktreeIntegration["status"],
    conflictPaths: [],
    diff: "",
    validationCommands: ["fixture-check"],
    validationResults: [],
    createdAt: "now",
    updatedAt: "now",
  };
}
const mergeCalls: WorktreeIntegrateRequest[] = [];
const rowsQueries: string[] = [];
const diffQueries: Parameters<IGitService["getDiff"]>[0][] = [];
function summary(): GitRepositorySummary {
  return {
    workspacePath,
    repoRoot: workspacePath,
    workspaceInRepoPath: ".",
    autoRefreshWatchPaths: [],
    branchName: "fixture",
    trackingBranchName: hasTracking ? "origin/fixture" : null,
    headRefType: "branch",
    ahead: 0,
    behind: 0,
    isDirty: dirtyPaths.length > 0,
    isGitAvailable: true,
    isRepository: true,
  };
}
function file(path: string): GitFileChange {
  return {
    path,
    repoRelativePath: path,
    workspaceRelativePath: path,
    kind: "modified",
    section: "unstaged",
    added: 1,
    removed: 0,
    isStaged: false,
    isUntracked: false,
    isConflicted: false,
  };
}
const clipboardCopies: string[] = [];
const fixturePlatform = {
  ...platform,
  async writeClipboardText(text: string) {
    clipboardCopies.push(text);
  },
};
const publishFixture = createPublishFixture(summary);
const fixtureReviews = new Map<string, GitCommitReview>();
let settings: AppSettings = {
  // 项目默认执行方式故意设为工作树；既有本地会话的文案仍须依据实际绑定。
  defaultSessionExecutionMode: "worktree",
  autoGenerateGitCommitMessage: true,
  ...(new URLSearchParams(location.search).has("reviewMode")
    ? {
        gitCommitReviewMode: gitCommitReviewModeSchema.parse(
          new URLSearchParams(location.search).get("reviewMode"),
        ),
      }
    : {}),
};
const gitService = {
  ...publishFixture.service,
  ...createReviewWorkspaceFixture(),
  async getCommitReview({ reviewId }: { reviewId: string }) {
    const review = fixtureReviews.get(reviewId);
    if (!review) return null;
    const committed = new Set(
      publishFixture.controls.calls
        .filter((call) => call.method === "commit")
        .map((call) => (call.params as { review?: { id: string; groupId: string } }).review)
        .filter((selection) => selection?.id === reviewId)
        .map((selection) => selection!.groupId),
    );
    for (const receipt of fixtureIntegration?.sourceReceipts ?? [])
      if (receipt.reviewId === reviewId) committed.add(receipt.groupId);
    const position = review.groups.findIndex((group) => !committed.has(group.id));
    return { review, position: position < 0 ? review.groups.length : position };
  },
  async getDiff(params) {
    diffQueries.push(params);
    const { path } = params;
    return {
      path,
      availability: "patch",
      patch: `diff --git a/${path} b/${path}\n--- a/${path}\n+++ b/${path}\n@@ -1 +1 @@\n-before\n+after\n`,
      beforeContent: "before",
      afterContent: "after",
    };
  },
  async getLocalBranches() {
    return {
      headRefType: "branch",
      currentBranchName: "L-GO",
      branches: ["L-GO", "main", "fixture"].map((name) => ({
        name,
        isCurrent: name === "L-GO",
        upstreamName: null,
        commitHash: "base",
        commitTimestampMs: null,
      })),
    };
  },
  async refresh(params) {
    if (params.includeIdentity && loadFailure) {
      const error = loadFailure;
      loadFailure = null;
      throw error;
    }
    return {
      summary: summary(),
      stagedChanges: [],
      unstagedChanges: dirtyPaths.map(file),
      identity: {
        userName: "Fixture",
        userEmail: "fixture@example.invalid",
        nameSource: "fixture",
        emailSource: "fixture",
      },
    };
  },
  async generateCommitMessage(params) {
    calls.push(params);
    if (failGenerate) {
      failGenerate = false;
      throw new Error("fixture-generation-failure");
    }
    if (holdGenerate) {
      holdGenerate = false;
      await new Promise<void>((resolve) => {
        releaseGeneration = resolve;
      });
    }
    const message = `修复 ${params.conversationContext?.sessionId ?? "fixture"} 的布局适配`;
    if (reviewUnavailable)
      return {
        message,
        providerId: "fixture",
        model: "fixture",
        reviewError: "内容审核不可用，请重新审核",
      };
    const included = (params.currentSessionFilePaths ?? dirtyPaths).filter(
      (path) => !(params.excludedFilePaths ?? []).includes(path),
    );
    if (included.length === 0) throw new Error("fixture-empty-review: 没有可审核的文件");
    const groups = groupedReview ? ["first", "second"] : ["group"];
    const review: GitCommitReview = {
      id: `review-${calls.length}`,
      mode: groupedReview ? "ordered" : "merged",
      warnings: groupedReview ? ["fixture-review-warning"] : [],
      groups: groups.map((id, position) => ({
        id,
        label: groupedReview ? `审核组 ${position + 1}` : "当前会话变更",
        sessionIds: [params.conversationContext?.sessionId ?? "fixture"],
        message: position === 0 ? message : "feat: 第二组修改",
        dependsOn: position === 0 ? [] : [groups[position - 1]],
        requiresConfirmation: true,
        files: included.map((path) => ({
          path,
          added: 1,
          removed: 0,
          patch: `diff --git a/${path} b/${path}\n+fixture change`,
        })),
      })),
    };
    fixtureReviews.set(review.id, review);
    return { message, providerId: "fixture", model: "fixture", review };
  },
} as IGitService;
const services = {
  gitService,
  settingService: {
    get: async () => structuredClone(settings),
    update: async (patch: Partial<AppSettings>) => {
      settings = { ...settings, ...patch };
    },
  },
  worktreeService: {
    getCapabilities: async () => ({
      supported: true,
      create: true,
      integrate: true,
      archive: true,
      restore: true,
      head: "s".repeat(40),
    }),
    getIntegration: async () => fixtureIntegration,
    integrate: async (params: WorktreeIntegrateRequest) => {
      mergeCalls.push(params);
      fixtureIntegration = {
        id: "fixture-integration",
        bindingId: "fixture-binding",
        requestId: params.requestId,
        sourceHead: "s".repeat(40),
        targetHead: "t".repeat(40),
        mergeBase: "b".repeat(40),
        targetBranch: params.targetBranch,
        targetPath: workspacePath,
        checkoutPath: "/fixture/integration",
        candidateHead: "c".repeat(40),
        status: "awaiting-review",
        conflictPaths: [],
        diff: "diff --git a/a.ts b/a.ts\n--- a/a.ts\n+++ b/a.ts\n@@ -1 +1 @@\n-before\n+after\n",
        validationCommands: ["fixture-check"],
        validationResults: [],
        createdAt: "now",
        updatedAt: "now",
        sourceReceipts: params.sourceCommits?.map((command) => ({
          reviewId: command.review!.id,
          groupId: command.review!.groupId,
          commitHash: "s".repeat(40),
        })),
      };
      return fixtureIntegration;
    },
    getBinding: async () =>
      ({
        id: "fixture-binding",
        taskId: "a",
        requestId: "fixture-request",
        originalWorkspacePath: workspacePath,
        originalWorkspaceIdentity: workspaceIdentity,
        workspacePath: "/fixture/worktrees/a",
        checkoutPath: "/fixture/worktrees/a",
        repositoryRoot: workspacePath,
        commonDirectory: `${workspacePath}/.git`,
        branch: "fixture",
        targetBranch: "L-GO",
        baseCommit: "base",
        sourceFolderPaths: [],
        status: "ready",
        createdAt: "now",
        updatedAt: "now",
        latestIntegrationId: fixtureIntegration?.id,
      }) satisfies WorktreeBinding,
  },
  lcodeAgentService: {
    async listSessionSubagents({ sessionId }: { sessionId: string }) {
      return {
        revision: 1,
        childSessionIds: sessionId === "workflow" ? ["actor"] : [],
        running: [],
        ended: { total: 0, items: [] },
      };
    },
  },
} as unknown as IServiceAccessor;
if (useProductionSidePane) {
  const registry = useRemoteWorkspaceSessionStore.getState();
  registry.registerBaseServices(services);
  if (previewRemoteSessionId && workspaceIdentity) {
    // 远程 identity 必须有已注册的 attachment 桩，不能让差异请求回落到本地服务。
    registry.registerSession({ sessionId: previewRemoteSessionId, services });
    registry.bindWorkspaceIdentity(workspaceIdentity, previewRemoteSessionId);
    const executionIdentity = replaceRemoteWorkspaceIdentityPath(
      workspaceIdentity,
      "/fixture/worktrees/a",
    );
    if (executionIdentity)
      registry.bindWorkspaceIdentity(executionIdentity, previewRemoteSessionId);
  }
}
const conversation = {
  async rowsRange({ sessionId }: { sessionId: string }) {
    rowsQueries.push(sessionId);
    const hasChanges = ["a", "b", "actor"].includes(sessionId);
    const rows: ConversationRow[] = hasChanges
      ? [
          {
            kind: "turnHeader",
            rowId: 1,
            entityId: "turn",
            turnId: "turn",
            origin: "userInput",
            state: "completedSuccess",
            startedAt: 1,
            createdAt: 1,
            createdAtSeq: 1,
            fileChanges: { files: 1, additions: 1, deletions: 0, state: "active" },
          } as ConversationRow,
        ]
      : [];
    return { rows, hasMore: false, atRevision: 1, atSeq: 1, atLogEpoch: sessionId };
  },
  async fileChanges({ sessionId }: { sessionId: string }) {
    return {
      files: 1,
      additions: 1,
      deletions: 0,
      state: "active",
      items: [
        {
          path: sessionId === "actor" ? "workflow.ts" : `${sessionId}.ts`,
          additions: 1,
          deletions: 0,
          writeCount: 1,
          toolNames: ["Edit"],
          patches: [],
        },
      ],
    };
  },
} as unknown as V4ConversationContextValue;

function FixtureApp() {
  const { update } = useSettings();
  const reviewPolicy = useProjectExecutionPolicy(workspacePath, workspaceIdentity).policy;
  const [panelVariant, setPanelVariant] = useState<"mini" | "panel" | null>("mini");
  const [sessionId, setSessionId] = useState("a");
  const [composerDraft, setComposerDraft] = useState("待发送的草稿不能改变");
  useGitFailureDraftReceiver(workspacePath, workspaceIdentity, sessionId, (text) =>
    setComposerDraft((current) => appendGitFailureDraft(current, text)),
  );
  const [executionBindingId, setExecutionBindingId] = useState<string | undefined>();
  const executionWorkspacePath = executionBindingId ? "/fixture/worktrees/a" : workspacePath;
  const executionWorkspaceIdentity =
    executionBindingId && useProductionSidePane
      ? workspaceIdentity
        ? (replaceRemoteWorkspaceIdentityPath(workspaceIdentity, executionWorkspacePath) ??
          undefined)
        : undefined
      : workspaceIdentity;
  const [logEpoch, setLogEpoch] = useState("epoch-a");
  const [enabled, setEnabled] = useState(true);
  const [revision, setRevision] = useState(0);
  const [request, setRequest] = useState<ManualGitCommitMessageRequest | null>(null);
  const [pending, setPending] = useState<string | null>(null);
  const [hidden, setHidden] = useState(false);
  const [automaticDraft, setAutomaticDraft] = useState<AutoGeneratedGitCommitMessageDraft | null>(
    null,
  );
  const scopeKey = buildGitCommitMessageScopeKey(
    JSON.stringify([workspaceIdentity?.trim() || workspacePath, "remote-fixture", sessionId]),
    logEpoch,
  );
  const eligible = canGenerateSessionCommitSummary({
    enabled,
    sessionId,
    readOnly: false,
    sideChat: false,
    phase: "completedSuccess",
    repositoryAvailable: true,
    repositoryDirty: dirtyPaths.length > 0,
  });
  const paths = useSessionCommitMessageFiles({
    enabled: eligible,
    scopeKey,
    sessionId,
    workspacePath,
    workspaceIdentity,
    remoteSessionId: "fixture-remote",
    candidatePathsKey: "[]",
    childSessionIdsKey: "[]",
    refreshKey: `${revision}`,
  });
  (globalThis as typeof globalThis & { __gitCommitFixture: unknown }).__gitCommitFixture = {
    calls,
    mergeCalls,
    rowsQueries,
    diffQueries,
    publish: publishFixture.controls,
    clipboardCopies,
    groups: (enabled: boolean) => {
      groupedReview = enabled;
    },
    tracked: () => {
      hasTracking = true;
      setRevision((value) => value + 1);
    },
    switchSession: (id: string) => {
      setSessionId(id);
      setRequest(null);
      setPending(null);
    },
    executionMode: (mode: "local" | "worktree") => {
      setExecutionBindingId(mode === "worktree" ? "fixture-binding" : undefined);
      setRequest(null);
      setPending(null);
      setAutomaticDraft(null);
    },
    setting: (value: boolean) => setEnabled(value),
    reviewMode: (mode: GitCommitReviewMode) => update({ gitCommitReviewMode: mode }),
    logEpoch: (value: string) => setLogEpoch(value),
    dirty: (paths: string[]) => {
      dirtyPaths = paths;
      setRevision((value) => value + 1);
    },
    failLoad: (message = "fixture-load-failure", code?: string) => {
      loadFailure = Object.assign(new Error(message), { code });
    },
    failGenerate: () => {
      failGenerate = true;
    },
    reviewUnavailable: () => {
      reviewUnavailable = true;
    },
    holdGeneration: () => {
      holdGenerate = true;
    },
    release: () => {
      releaseGeneration?.();
      releaseGeneration = null;
    },
    hideMenu: () => setHidden(true),
    rerender: () => setRevision((value) => value + 1),
    automatic: (unavailable = false) => {
      const message = "自动生成的中文提交纪要";
      const automatic: AutoGeneratedGitCommitMessageDraft = {
        key: `automatic-${++requestSequence}`,
        scopeKey,
        message,
        currentSessionFilePaths: ["a.ts"],
        gitFingerprint: buildGitChangesFingerprint({
          files: dirtyPaths.map(file),
          currentSessionFilePaths: ["a.ts"],
          gitSummary: summary(),
          workspacePath,
        })!,
        review: {
          id: "automatic-review",
          mode: "merged",
          warnings: [],
          groups: [
            {
              id: "automatic-group",
              label: "当前会话",
              sessionIds: [sessionId],
              dependsOn: [],
              message,
              requiresConfirmation: true,
              files: [{ path: "a.ts", patch: "+fixture", added: 1, removed: 0 }],
            },
          ],
        },
        ...(unavailable ? { review: undefined, reviewError: "内容审核不可用，请重新审核" } : {}),
      };
      if (automatic.review) fixtureReviews.set(automatic.review.id, automatic.review);
      setAutomaticDraft(automatic);
    },
  };
  return (
    <div className="p-4 text-foreground">
      <FixtureReviewPreview
        panel={
          useProductionSidePane
            ? {
                workspacePath,
                workspaceIdentity,
                executionPath: executionWorkspacePath,
                executionIdentity: executionWorkspaceIdentity,
                remoteSessionId: previewRemoteSessionId,
                sessionId,
              }
            : undefined
        }
        onSource={(source) =>
          Object.assign(globalThis.__gitCommitFixture, { previewSource: source })
        }
      />
      <p data-testid="session">{sessionId}</p>
      <p data-testid="review-mode">{reviewPolicy.gitCommitReviewMode}</p>
      <p data-testid="automatic-ready">{automaticDraft?.key}</p>
      <textarea
        data-testid="composer-draft"
        value={composerDraft}
        onChange={(event) => setComposerDraft(event.target.value)}
      />
      <div className="flex items-center justify-end gap-1">
        <button type="button">发送</button>
        <ConversationCommitMessageButton
          pending={pending !== null}
          onClick={
            eligible && paths.length > 0
              ? () => {
                  const key = `${scopeKey}/${++requestSequence}`;
                  setPending(key);
                  setRequest({
                    key,
                    scopeKey,
                    currentSessionFilePaths: paths,
                    conversationContext: {
                      sessionId,
                      messages: [{ role: "user", content: `修复 ${sessionId} 的布局` }],
                    },
                  });
                }
              : undefined
          }
        />
      </div>
      <div className={hidden ? "hidden" : ""}>
        {showStatusPanel ? (
          <ConversationStatusPanel
            workspaceRemoteSessionId={previewRemoteSessionId}
            workspacePath={executionWorkspacePath}
            workspaceIdentity={executionWorkspaceIdentity}
            originWorkspacePath={workspacePath}
            originWorkspaceIdentity={workspaceIdentity}
            executionSessionId={sessionId}
            reviewEpoch={logEpoch}
            executionBindingId={executionBindingId}
            gitSummary={summary()}
            onRefreshGit={() => setRevision((value) => value + 1)}
            commitDialogScopeKey={scopeKey}
            layoutMode="inline"
            summaryPanelVariantOverride={panelVariant}
            onVariantChange={setPanelVariant}
            isMobileViewport
          />
        ) : (
          <GitActionMenu
            key={scopeKey}
            workspaceRemoteSessionId={previewRemoteSessionId}
            workspacePath={executionWorkspacePath}
            workspaceIdentity={executionWorkspaceIdentity}
            originWorkspacePath={workspacePath}
            originWorkspaceIdentity={workspaceIdentity}
            executionSessionId={sessionId}
            reviewEpoch={logEpoch}
            executionBindingId={executionBindingId}
            dialogScopeKey={scopeKey}
            gitSummary={summary()}
            manualCommitMessageRequest={request}
            autoGeneratedCommitMessageDraft={automaticDraft}
            onManualCommitMessageSettled={(key) => {
              setPending((prior) => (prior === key ? null : prior));
              setRequest((prior) => (prior?.key === key ? null : prior));
            }}
            onRefreshGit={() => setRevision((value) => value + 1)}
          />
        )}
      </div>
    </div>
  );
}
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <ServiceProvider services={services}>
      <PlatformProvider platform={fixturePlatform}>
        <LCodeIntlProvider
          initialLocale={new URLSearchParams(location.search).has("english") ? "en-US" : "zh-CN"}
        >
          <TooltipProvider>
            <TabStoreProvider>
              <V4ConversationContext.Provider value={conversation}>
                <FixtureApp />
              </V4ConversationContext.Provider>
            </TabStoreProvider>
          </TooltipProvider>
        </LCodeIntlProvider>
      </PlatformProvider>
    </ServiceProvider>
  </StrictMode>,
);
