import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import type { IServiceAccessor } from "@lcode/services";
import type { GitCommitReview, GitFileChange, GitRepositorySummary } from "@lcode/shared";
import { GitActionMenu } from "@/GitActionMenu.js";
import { ServiceProvider } from "@/hooks/useServices.js";
import { LCodeIntlProvider } from "@/i18n/IntlProvider.js";
import { TooltipProvider } from "@/components/ui/tooltip.js";
import { buildGitChangesFingerprint } from "@/git-action-menu/currentSessionFileScope.js";
import type { AutoGeneratedGitCommitMessageDraft } from "@/git-action-menu/autoCommitMessage.js";
import "@lcode/ui/styles.css";

// 仅浏览器夹具：无真实仓库、模型、凭据或平台副作用。
const workspace = "C:/fixture";
const summary: GitRepositorySummary = {
  workspacePath: workspace,
  repoRoot: workspace,
  workspaceInRepoPath: ".",
  autoRefreshWatchPaths: [],
  branchName: "fixture",
  trackingBranchName: null,
  headRefType: "branch",
  ahead: 0,
  behind: 0,
  isDirty: true,
  isRepository: true,
  isGitAvailable: true,
};
const files: GitFileChange[] = ["a.ts", "b.ts"].map((path) => ({
  path: `${workspace}/${path}`,
  repoRelativePath: path,
  workspaceRelativePath: path,
  kind: "modified",
  section: "unstaged",
  added: 1,
  removed: 0,
  isStaged: false,
  isUntracked: false,
  isConflicted: false,
}));
const review: GitCommitReview = {
  id: "fixture-review",
  mode: "merged",
  warnings: [],
  groups: [
    {
      id: "merged",
      sessionIds: [],
      label: "功能 A",
      dependsOn: [],
      message: "feat: 增强中文功能",
      requiresConfirmation: true,
      files: [{ path: "a.ts", patch: "+中文功能\n", added: 1, removed: 0 }],
    },
  ],
};
const fingerprint = buildGitChangesFingerprint({
  files,
  currentSessionFilePaths: ["a.ts"],
  gitSummary: summary,
  workspacePath: workspace,
})!;
let calls = { stage: 0, commit: 0, generate: 0 };
const services = {
  gitService: {
    refresh: async () => ({
      summary,
      unstagedChanges: files,
      stagedChanges: [],
      identity: { userName: "Fixture", userEmail: "fixture@example.invalid" },
    }),
    generateCommitMessage: async () => {
      calls.generate++;
      return { message: "feat: 重新生成中文功能", review, providerId: "fixture", model: "fixture" };
    },
    stage: async () => {
      calls.stage++;
    },
    commit: async () => {
      calls.commit++;
      throw new Error("夹具不执行真实提交");
    },
  },
} as unknown as IServiceAccessor;

function Fixture() {
  const [mode, setMode] = useState("success");
  const [generation, setGeneration] = useState(0);
  const [draft, setDraft] = useState<AutoGeneratedGitCommitMessageDraft | null>(null);
  useEffect(() => {
    const complete = (event: KeyboardEvent) => {
      if (event.key !== "F8") return;
      const failed = mode === "failed" || mode === "failed-stale";
      setDraft({
        key: `completion-${generation}-${Date.now()}`,
        currentSessionFilePaths: ["a.ts"],
        gitFingerprint: mode.includes("stale") ? "expired" : fingerprint,
        message: failed ? "" : review.groups[0]!.message,
        ...(failed ? { reviewError: "文本审核失败，请重新生成或明确选择手动提交。" } : { review }),
      });
    };
    document.addEventListener("keydown", complete);
    return () => document.removeEventListener("keydown", complete);
  }, [mode, generation]);
  return (
    <ServiceProvider services={services}>
      <LCodeIntlProvider initialLocale="zh-CN">
        <TooltipProvider>
          <main className="space-y-4 p-4 text-ui-base">
            <h1 className="text-ui-lg">Git 自动提交草稿回归（F8 模拟实时完成）</h1>
            <select
              aria-label="回归场景"
              value={mode}
              onChange={(event) => {
                setMode(event.target.value);
                setGeneration((value) => value + 1);
                setDraft(null);
                calls = { stage: 0, commit: 0, generate: 0 };
              }}
            >
              <option value="success">有效中文草稿</option>
              <option value="failed">生成失败</option>
              <option value="stale">成功但过期</option>
              <option value="failed-stale">失败且过期</option>
            </select>
            <GitActionMenu
              key={generation}
              workspacePath={workspace}
              gitSummary={summary}
              activeTaskChangeSummary={{
                fileCount: files.length,
                added: 2,
                removed: 0,
                files: files.map((file) => ({
                  path: file.path,
                  added: 1,
                  removed: 0,
                  writeCount: 1,
                  lastTurnIndex: 0,
                })),
              }}
              autoGeneratedCommitMessageDraft={draft}
              onRefreshGit={() => {}}
            />
            <output data-testid="fixture-calls">{JSON.stringify(calls)}</output>
          </main>
        </TooltipProvider>
      </LCodeIntlProvider>
    </ServiceProvider>
  );
}
createRoot(document.getElementById("root")!).render(<Fixture />);
