import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  InstalledAppLauncherError,
  createInstalledAppLauncher,
  normalizeInstalledAppLookupKey,
  normalizeInstalledAppName,
} from "./installed-app-launcher.js";

test("normalizes generic Windows launcher suffixes without a product whitelist", () => {
  assert.equal(normalizeInstalledAppName("QQ"), "qq");
  assert.equal(normalizeInstalledAppName("QQScLauncher.exe"), "qq");
  assert.equal(normalizeInstalledAppName("Example Client Launcher"), "example");
});

test("only Windows folds launcher suffixes in lookup keys", () => {
  assert.equal(
    normalizeInstalledAppLookupKey({ name: "Foo" }, "win32"),
    normalizeInstalledAppLookupKey({ name: "FooLauncher" }, "win32"),
  );
  assert.notEqual(
    normalizeInstalledAppLookupKey({ name: "Foo" }, "darwin"),
    normalizeInstalledAppLookupKey({ name: "FooLauncher" }, "darwin"),
  );
  assert.notEqual(
    normalizeInstalledAppLookupKey({ name: "Foo" }, "linux"),
    normalizeInstalledAppLookupKey({ name: "FooLauncher" }, "linux"),
  );
});

test("Windows resolves Start Apps uniquely and launches with argument arrays", async () => {
  const calls = [];
  const launcher = createInstalledAppLauncher({
    platform: "win32",
    async run(command) {
      calls.push(command);
      if (command.file === "powershell.exe") {
        return {
          stdout: JSON.stringify([
            { Name: "QQScLauncher", AppID: "Tencent.QQScLauncher_abc!QQScLauncher" },
            { Name: "Notepad", AppID: "Microsoft.WindowsNotepad_abc!App" },
          ]),
          stderr: "",
        };
      }
      return { stdout: "", stderr: "" };
    },
  });

  const app = await launcher.launch({ name: "QQ" });
  assert.equal(app.name, "QQScLauncher");
  assert.deepEqual(calls[1], {
    file: "explorer.exe",
    args: ["shell:AppsFolder\\Tencent.QQScLauncher_abc!QQScLauncher"],
    signal: calls[1].signal,
    waitForExit: false,
  });
  assert.ok(calls[1].signal instanceof AbortSignal);
  await launcher.dispose();
});

test("Windows resolves the exact localized Start Apps identity without launching it", async () => {
  const launcher = createInstalledAppLauncher({
    platform: "win32",
    async run(command) {
      return command.file === "powershell.exe"
        ? {
            stdout: JSON.stringify([
              { Name: "微信", AppID: "Microsoft.AutoGenerated.{guid}" },
              { Name: "Weixin", AppID: "D:\\Tencent\\Weixin\\Weixin.exe" },
            ]),
            stderr: "",
          }
        : { stdout: "", stderr: "" };
    },
  });

  const app = await launcher.resolve({ name: "微信" });
  assert.equal(app.name, "微信");
  assert.equal(app.appId, "Microsoft.AutoGenerated.{guid}");
  await launcher.dispose();
});

test("Windows directly starts an absolute executable returned by Get-StartApps", async () => {
  const calls = [];
  const executable = "D:\\Tencent\\QQ\\Bin\\QQScLauncher.exe";
  const launcher = createInstalledAppLauncher({
    platform: "win32",
    async run(command) {
      calls.push(command);
      return command.file === "powershell.exe"
        ? {
            stdout: JSON.stringify({ Name: "QQScLauncher", AppID: executable }),
            stderr: "",
          }
        : { stdout: "", stderr: "" };
    },
  });

  await launcher.launch({ name: "QQ" });
  assert.equal(calls.at(-1).file, executable);
  assert.deepEqual(calls.at(-1).args, []);
  assert.equal(calls.at(-1).cwd, "D:\\Tencent\\QQ\\Bin");
  assert.equal(calls.at(-1).waitForExit, false);
});

test("Windows accepts the Start Apps AppID as the platform bundle_id", async () => {
  const calls = [];
  const appId = "Tencent.QQScLauncher_abc!QQScLauncher";
  const launcher = createInstalledAppLauncher({
    platform: "win32",
    async run(command) {
      calls.push(command);
      return command.file === "powershell.exe"
        ? { stdout: JSON.stringify({ Name: "QQScLauncher", AppID: appId }), stderr: "" }
        : { stdout: "", stderr: "" };
    },
  });

  const app = await launcher.launch({ bundle_id: appId });
  assert.equal(app.appId, appId);
  assert.deepEqual(calls.at(-1).args, [`shell:AppsFolder\\${appId}`]);
});

test("Windows rejects normalized ambiguity without starting either candidate", async () => {
  const calls = [];
  const launcher = createInstalledAppLauncher({
    platform: "win32",
    async run(command) {
      calls.push(command);
      return {
        stdout: JSON.stringify([
          { Name: "ChatLauncher", AppID: "chat-one" },
          { Name: "ChatScLauncher", AppID: "chat-two" },
        ]),
        stderr: "",
      };
    },
  });

  await assert.rejects(launcher.launch({ name: "Chat" }), (error) => {
    assert.ok(error instanceof InstalledAppLauncherError);
    assert.equal(error.code, "AMBIGUOUS_APP");
    return true;
  });
  assert.equal(calls.length, 1);
});

test("Windows prefers one exact identity before launcher-suffix fallback", async () => {
  const calls = [];
  const launcher = createInstalledAppLauncher({
    platform: "win32",
    async run(command) {
      calls.push(command);
      if (command.file === "powershell.exe") {
        return {
          stdout: JSON.stringify([
            { Name: "Chat", AppID: "chat-exact" },
            { Name: "ChatLauncher", AppID: "chat-launcher" },
          ]),
          stderr: "",
        };
      }
      return { stdout: "", stderr: "" };
    },
  });

  await launcher.launch({ name: "Chat" });
  assert.deepEqual(calls.at(-1).args, ["shell:AppsFolder\\chat-exact"]);
});

test("reports missing installations and command failures with stable codes", async () => {
  const missing = createInstalledAppLauncher({
    platform: "win32",
    async run() {
      return { stdout: "[]", stderr: "" };
    },
  });
  await assert.rejects(missing.launch({ name: "Missing" }), { code: "APP_NOT_FOUND" });

  const failed = createInstalledAppLauncher({
    platform: "win32",
    async run(command) {
      if (command.file === "powershell.exe") {
        return {
          stdout: JSON.stringify({ Name: "Example", AppID: "example" }),
          stderr: "",
        };
      }
      throw new Error("start failed");
    },
  });
  await assert.rejects(failed.launch({ name: "Example" }), { code: "LAUNCH_FAILED" });
});

test("macOS resolves bundle metadata and launches through open without a shell", async () => {
  const calls = [];
  const launcher = createInstalledAppLauncher({
    platform: "darwin",
    async run(command) {
      calls.push(command);
      if (command.file === "/usr/bin/mdfind") {
        return { stdout: "/Applications/Example.app\0", stderr: "" };
      }
      if (command.file === "/usr/bin/mdls") {
        const field = command.args[1];
        return {
          stdout: field === "kMDItemCFBundleIdentifier" ? "com.example.app\n" : "Example\n",
          stderr: "",
        };
      }
      return { stdout: "", stderr: "" };
    },
  });

  await launcher.launch({ bundle_id: "com.example.app" });
  assert.deepEqual(calls.at(-1).file, "/usr/bin/open");
  assert.deepEqual(calls.at(-1).args, ["-b", "com.example.app"]);
});

test("Linux parses XDG desktop entries and passes the file as a gio argument", async () => {
  const root = await mkdtemp(join(tmpdir(), "zcode-cua-launcher-"));
  try {
    const applications = join(root, "applications");
    await mkdir(applications);
    const desktopFile = join(applications, "example.desktop");
    await writeFile(
      desktopFile,
      "[Desktop Entry]\nType=Application\nName=Example\nExec=/opt/example/bin/example %U\n",
      "utf8",
    );
    const calls = [];
    const launcher = createInstalledAppLauncher({
      platform: "linux",
      env: { XDG_DATA_HOME: root, XDG_DATA_DIRS: "" },
      async run(command) {
        calls.push(command);
        return { stdout: "", stderr: "" };
      },
    });

    const app = await launcher.launch({ name: "example" });
    assert.equal(app.executable, "example");
    assert.equal(calls.length, 1);
    assert.equal(calls[0].file, "gio");
    assert.deepEqual(calls[0].args, ["launch", desktopFile]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("Linux resolves desktop-file bundle_id with user entries overriding system entries", async () => {
  const root = await mkdtemp(join(tmpdir(), "zcode-cua-launcher-priority-"));
  try {
    const userRoot = join(root, "user");
    const systemRoot = join(root, "system");
    const userApplications = join(userRoot, "applications");
    const systemApplications = join(systemRoot, "applications");
    await Promise.all([
      mkdir(userApplications, { recursive: true }),
      mkdir(systemApplications, { recursive: true }),
    ]);
    const userDesktopFile = join(userApplications, "example.desktop");
    await Promise.all([
      writeFile(
        userDesktopFile,
        "[Desktop Entry]\nType=Application\nName=Example User\nExec=/opt/user/example %U\n",
        "utf8",
      ),
      writeFile(
        join(systemApplications, "example.desktop"),
        "[Desktop Entry]\nType=Application\nName=Example System\nExec=/opt/system/example %U\n",
        "utf8",
      ),
    ]);
    const calls = [];
    const launcher = createInstalledAppLauncher({
      platform: "linux",
      env: { XDG_DATA_HOME: userRoot, XDG_DATA_DIRS: systemRoot },
      async run(command) {
        calls.push(command);
        return { stdout: "", stderr: "" };
      },
    });

    const app = await launcher.launch({ bundle_id: "example.desktop" });
    assert.equal(app.name, "Example User");
    assert.equal((await launcher.launch({ bundle_id: "example" })).name, "Example User");
    assert.equal(calls.length, 2);
    for (const call of calls) {
      assert.deepEqual(call, {
        file: "gio",
        args: ["launch", userDesktopFile],
        signal: call.signal,
      });
    }
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("Linux user Hidden entry suppresses the same system desktop-file id", async () => {
  const root = await mkdtemp(join(tmpdir(), "zcode-cua-launcher-hidden-"));
  try {
    const userRoot = join(root, "user");
    const systemRoot = join(root, "system");
    const userApplications = join(userRoot, "applications");
    const systemApplications = join(systemRoot, "applications");
    await Promise.all([
      mkdir(userApplications, { recursive: true }),
      mkdir(systemApplications, { recursive: true }),
    ]);
    await Promise.all([
      writeFile(
        join(userApplications, "example.desktop"),
        "[Desktop Entry]\nType=Application\nName=Example\nExec=/opt/user/example\nHidden=true\n",
        "utf8",
      ),
      writeFile(
        join(systemApplications, "example.desktop"),
        "[Desktop Entry]\nType=Application\nName=Example\nExec=/opt/system/example\n",
        "utf8",
      ),
    ]);
    const launcher = createInstalledAppLauncher({
      platform: "linux",
      env: { XDG_DATA_HOME: userRoot, XDG_DATA_DIRS: systemRoot },
      async run() {
        throw new Error("hidden desktop entry must not launch");
      },
    });

    await assert.rejects(launcher.launch({ bundle_id: "example.desktop" }), {
      code: "APP_NOT_FOUND",
    });
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
